# yaml-language-server: $schema=https://raw.githubusercontent.com/hpx7/delta-pack/refs/heads/main/schema.json

ExampleObject:
  stringField: string
  signedIntField: int
  unsignedIntField: uint
  floatField: float
  booleanField: boolean
