import assert from "assert";
import { GameState } from "./output5.ts";

const state1: GameState = {
  creatures: new Map([
    [
      1,
      {
        team: "blue",
        hero: false,
        creatureType: "kingBlue",
        equippedItemType: "kingSword",
        health: 492,
        maxHealth: 1000,
        visible: true,
        facing: "downLeft",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 49,
        y: 203,
      },
    ],
    [
      2,
      {
        team: "red",
        hero: false,
        creatureType: "kingRed",
        equippedItemType: "kingSword",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 578,
        y: 197,
      },
    ],
    [
      4,
      {
        team: "red",
        hero: false,
        creatureType: "towerGuard",
        equippedItemType: "towerGuardBow",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 468,
        y: 108,
      },
    ],
    [
      5,
      {
        team: "blue",
        hero: false,
        creatureType: "towerGuard",
        equippedItemType: "towerGuardBow",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 172,
        y: 276,
      },
    ],
    [
      6,
      {
        team: "red",
        hero: false,
        creatureType: "towerGuard",
        equippedItemType: "towerGuardBow",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 468,
        y: 276,
      },
    ],
    [
      46,
      {
        team: "blue",
        hero: false,
        creatureType: "necromancer",
        health: 200,
        maxHealth: 200,
        visible: true,
        facing: "upRight",
        moving: false,
        moveType: "walk",
        using: "raiseSkeletons",
        useDirection: "upRight",
        takingDamage: false,
        frozen: false,
        x: 192,
        y: 124,
      },
    ],
    [
      47,
      {
        team: "blue",
        hero: false,
        creatureType: "human",
        equippedItemType: "longsword",
        health: 110,
        maxHealth: 110,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 344,
        y: 113,
      },
    ],
    [
      48,
      {
        team: "blue",
        hero: false,
        creatureType: "human",
        equippedItemType: "longsword",
        health: 110,
        maxHealth: 110,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 339,
        y: 113,
      },
    ],
    [
      49,
      {
        team: "blue",
        hero: false,
        creatureType: "human",
        equippedItemType: "longsword",
        health: 110,
        maxHealth: 110,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 368,
        y: 111,
      },
    ],
    [
      50,
      {
        team: "blue",
        hero: false,
        creatureType: "human",
        equippedItemType: "longsword",
        health: 110,
        maxHealth: 110,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 326,
        y: 114,
      },
    ],
    [
      51,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 0,
        maxHealth: 100,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 251,
        y: 271,
      },
    ],
    [
      52,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "upLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 252,
        y: 283,
      },
    ],
    [
      53,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 252,
        y: 275,
      },
    ],
    [
      54,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "upLeft",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "left",
        takingDamage: false,
        frozen: false,
        x: 252,
        y: 279,
      },
    ],
    [
      55,
      {
        team: "blue",
        hero: false,
        creatureType: "skeleton",
        equippedItemType: "skeletonHands",
        health: 90,
        maxHealth: 90,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 227,
        y: 123,
      },
    ],
    [
      56,
      {
        team: "blue",
        hero: false,
        creatureType: "skeleton",
        equippedItemType: "skeletonHands",
        health: 90,
        maxHealth: 90,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 233,
        y: 125,
      },
    ],
    [
      57,
      {
        team: "blue",
        hero: false,
        creatureType: "skeleton",
        equippedItemType: "skeletonHands",
        health: 90,
        maxHealth: 90,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 235,
        y: 121,
      },
    ],
    [
      58,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 43,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 409,
        y: 101,
      },
    ],
    [
      59,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 408,
        y: 104,
      },
    ],
    [
      60,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 43,
        maxHealth: 70,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: true,
        frozen: false,
        x: 407,
        y: 107,
      },
    ],
    [
      61,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "upRight",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 409,
        y: 114,
      },
    ],
    [
      62,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "upRight",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 409,
        y: 110,
      },
    ],
    [
      63,
      {
        team: "red",
        hero: true,
        creatureType: "cleric",
        equippedItemType: "clericStaffDivineFire",
        health: 500,
        maxHealth: 500,
        visible: true,
        facing: "upLeft",
        moving: false,
        moveType: "walk",
        using: "spiritGuardians",
        useDirection: "upLeft",
        takingDamage: false,
        frozen: false,
        x: 507,
        y: 126,
      },
    ],
    [
      64,
      {
        team: "blue",
        hero: false,
        creatureType: "skeleton",
        equippedItemType: "skeletonHands",
        health: 90,
        maxHealth: 90,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "rise",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 205,
        y: 108,
      },
    ],
    [
      65,
      {
        team: "blue",
        hero: false,
        creatureType: "skeleton",
        equippedItemType: "skeletonHands",
        health: 90,
        maxHealth: 90,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "rise",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 212,
        y: 122,
      },
    ],
    [
      66,
      {
        team: "blue",
        hero: false,
        creatureType: "skeleton",
        equippedItemType: "skeletonHands",
        health: 90,
        maxHealth: 90,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "rise",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 208,
        y: 136,
      },
    ],
  ]),
  items: new Map(),
  effects: new Map([
    [
      680,
      {
        effectType: "visualEffect",
        visualEffectType: "spiritGuardiansPrayer",
        direction: "upLeft",
        x: 507,
        y: 126,
      },
    ],
    [
      686,
      {
        creatureId: 4,
        effectType: "weaponEffect",
        weaponEffectType: "projectile",
        projectileType: "arrow",
        weaponType: "towerGuardBow",
        direction: "left",
        angle: 146,
        x: 410,
        y: 109,
      },
    ],
    [
      687,
      {
        creatureId: 58,
        effectType: "weaponEffect",
        weaponEffectType: "projectile",
        projectileType: "pebble",
        weaponType: "slingshot",
        direction: "right",
        angle: 7,
        x: 438,
        y: 104,
      },
    ],
  ]),
  objects: new Map([
    [
      17,
      {
        team: "red",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: true,
        towerName: "topRight",
        width: 24,
        height: 24,
        durability: 985,
        maxDurability: 1000,
        x: 468,
        y: 108,
      },
    ],
    [
      18,
      {
        team: "red",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: true,
        towerName: "bottomRight",
        width: 24,
        height: 24,
        durability: 1000,
        maxDurability: 1000,
        x: 468,
        y: 276,
      },
    ],
    [
      19,
      {
        team: "blue",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: true,
        towerName: "bottomLeft",
        width: 24,
        height: 24,
        durability: 714,
        maxDurability: 1000,
        x: 172,
        y: 276,
      },
    ],
    [
      20,
      {
        team: "blue",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: false,
        towerName: "topLeft",
        width: 24,
        height: 24,
        durability: 503,
        maxDurability: 1000,
        x: 172,
        y: 108,
      },
    ],
  ]),
  players: new Map([
    [
      "yvVTRec9OYBq",
      {
        name: "Lime Moth",
        team: "blue",
        randomSlots: [],
        restrictionZones: "",
      },
    ],
    [
      "iSfj9vIZlNIJK0BvpgW9iiEJErzdWVP8",
      {
        name: "Aseph",
        team: "red",
        hero: 63,
        cents: 260,
        deck: {
          card1: "cleric",
          card2: "goblinCatapult",
          card3: "golem",
          card4: "offenseUp",
          card5: "elf",
          card6: "halfling",
          card7: "goblin",
          card8: "healthPotion",
        },
        randomSlots: [],
        hand: {
          slot1: "halfling",
          slot2: "healthPotion",
          slot3: "goblin",
          slot4: "goblinCatapult",
        },
        skills: {
          slot1: {
            type: "spiritGuardians",
            inUse: true,
            cooldown: 0,
            cooldownTotal: 0,
          },
          slot2: {
            type: "wordOfPain",
            inUse: false,
            cooldown: 1248,
            cooldownTotal: 4400,
          },
          slot3: {
            type: "healingWord",
            inUse: false,
            cooldown: 1248,
            cooldownTotal: 4400,
          },
        },
        restrictionZones: "blueBase,bottomLeft,topLeft",
      },
    ],
  ]),
  spectators: new Map(),
  info: {
    timeElapsed: 66,
  },
};

const encoded = GameState.encode(state1);
console.log("encoded", encoded);
// Uint8Array(1045)

const decoded = GameState.decode(encoded);
assert(GameState.equals(decoded, state1));

const state2: GameState = {
  creatures: new Map([
    [
      1,
      {
        team: "blue",
        hero: false,
        creatureType: "kingBlue",
        equippedItemType: "kingSword",
        health: 492,
        maxHealth: 1000,
        visible: true,
        facing: "downLeft",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 48,
        y: 203,
      },
    ],
    [
      2,
      {
        team: "red",
        hero: false,
        creatureType: "kingRed",
        equippedItemType: "kingSword",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 579,
        y: 197,
      },
    ],
    [
      4,
      {
        team: "red",
        hero: false,
        creatureType: "towerGuard",
        equippedItemType: "towerGuardBow",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 468,
        y: 108,
      },
    ],
    [
      5,
      {
        team: "blue",
        hero: false,
        creatureType: "towerGuard",
        equippedItemType: "towerGuardBow",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 172,
        y: 276,
      },
    ],
    [
      6,
      {
        team: "red",
        hero: false,
        creatureType: "towerGuard",
        equippedItemType: "towerGuardBow",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 468,
        y: 276,
      },
    ],
    [
      46,
      {
        team: "blue",
        hero: false,
        creatureType: "necromancer",
        health: 200,
        maxHealth: 200,
        visible: true,
        facing: "upRight",
        moving: false,
        moveType: "walk",
        using: "raiseSkeletons",
        useDirection: "upRight",
        takingDamage: false,
        frozen: false,
        x: 192,
        y: 124,
      },
    ],
    [
      47,
      {
        team: "blue",
        hero: false,
        creatureType: "human",
        equippedItemType: "longsword",
        health: 110,
        maxHealth: 110,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 345,
        y: 113,
      },
    ],
    [
      48,
      {
        team: "blue",
        hero: false,
        creatureType: "human",
        equippedItemType: "longsword",
        health: 110,
        maxHealth: 110,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 340,
        y: 113,
      },
    ],
    [
      49,
      {
        team: "blue",
        hero: false,
        creatureType: "human",
        equippedItemType: "longsword",
        health: 110,
        maxHealth: 110,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 369,
        y: 111,
      },
    ],
    [
      50,
      {
        team: "blue",
        hero: false,
        creatureType: "human",
        equippedItemType: "longsword",
        health: 110,
        maxHealth: 110,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 327,
        y: 114,
      },
    ],
    [
      51,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 0,
        maxHealth: 100,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 251,
        y: 271,
      },
    ],
    [
      52,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "upLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 252,
        y: 283,
      },
    ],
    [
      53,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 252,
        y: 275,
      },
    ],
    [
      54,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "upLeft",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "left",
        takingDamage: false,
        frozen: false,
        x: 252,
        y: 279,
      },
    ],
    [
      55,
      {
        team: "blue",
        hero: false,
        creatureType: "skeleton",
        equippedItemType: "skeletonHands",
        health: 90,
        maxHealth: 90,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 227,
        y: 123,
      },
    ],
    [
      56,
      {
        team: "blue",
        hero: false,
        creatureType: "skeleton",
        equippedItemType: "skeletonHands",
        health: 90,
        maxHealth: 90,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 233,
        y: 124,
      },
    ],
    [
      57,
      {
        team: "blue",
        hero: false,
        creatureType: "skeleton",
        equippedItemType: "skeletonHands",
        health: 90,
        maxHealth: 90,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 235,
        y: 121,
      },
    ],
    [
      58,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 43,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 409,
        y: 101,
      },
    ],
    [
      59,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 408,
        y: 102,
      },
    ],
    [
      60,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 43,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: true,
        frozen: false,
        x: 408,
        y: 107,
      },
    ],
    [
      61,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "upRight",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 409,
        y: 114,
      },
    ],
    [
      62,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "upRight",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 409,
        y: 110,
      },
    ],
    [
      63,
      {
        team: "red",
        hero: true,
        creatureType: "cleric",
        equippedItemType: "clericStaffDivineFire",
        health: 500,
        maxHealth: 500,
        visible: true,
        facing: "upLeft",
        moving: false,
        moveType: "walk",
        using: "spiritGuardians",
        useDirection: "upLeft",
        takingDamage: false,
        frozen: false,
        x: 507,
        y: 126,
      },
    ],
    [
      64,
      {
        team: "blue",
        hero: false,
        creatureType: "skeleton",
        equippedItemType: "skeletonHands",
        health: 90,
        maxHealth: 90,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "rise",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 205,
        y: 108,
      },
    ],
    [
      65,
      {
        team: "blue",
        hero: false,
        creatureType: "skeleton",
        equippedItemType: "skeletonHands",
        health: 90,
        maxHealth: 90,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "rise",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 212,
        y: 122,
      },
    ],
    [
      66,
      {
        team: "blue",
        hero: false,
        creatureType: "skeleton",
        equippedItemType: "skeletonHands",
        health: 90,
        maxHealth: 90,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "rise",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 208,
        y: 136,
      },
    ],
    [
      67,
      {
        team: "red",
        hero: false,
        creatureType: "spiritGuardian",
        equippedItemType: "spiritGuardianSword",
        health: 75,
        maxHealth: 75,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "summon",
        useDirection: "left",
        takingDamage: false,
        frozen: false,
        x: 411,
        y: 91,
      },
    ],
    [
      68,
      {
        team: "red",
        hero: false,
        creatureType: "spiritGuardian",
        equippedItemType: "spiritGuardianSword",
        health: 75,
        maxHealth: 75,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "summon",
        useDirection: "left",
        takingDamage: false,
        frozen: false,
        x: 425,
        y: 99,
      },
    ],
    [
      69,
      {
        team: "red",
        hero: false,
        creatureType: "spiritGuardian",
        equippedItemType: "spiritGuardianSword",
        health: 75,
        maxHealth: 75,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "summon",
        useDirection: "left",
        takingDamage: false,
        frozen: false,
        x: 425,
        y: 115,
      },
    ],
    [
      70,
      {
        team: "red",
        hero: false,
        creatureType: "spiritGuardian",
        equippedItemType: "spiritGuardianSword",
        health: 75,
        maxHealth: 75,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "summon",
        useDirection: "left",
        takingDamage: false,
        frozen: false,
        x: 411,
        y: 123,
      },
    ],
    [
      71,
      {
        team: "red",
        hero: false,
        creatureType: "spiritGuardian",
        equippedItemType: "spiritGuardianSword",
        health: 75,
        maxHealth: 75,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "summon",
        useDirection: "left",
        takingDamage: false,
        frozen: false,
        x: 397,
        y: 115,
      },
    ],
    [
      72,
      {
        team: "red",
        hero: false,
        creatureType: "spiritGuardian",
        equippedItemType: "spiritGuardianSword",
        health: 75,
        maxHealth: 75,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "summon",
        useDirection: "left",
        takingDamage: false,
        frozen: false,
        x: 397,
        y: 99,
      },
    ],
  ]),
  items: new Map(),
  effects: new Map([
    [
      680,
      {
        effectType: "visualEffect",
        visualEffectType: "spiritGuardiansPrayer",
        direction: "upLeft",
        x: 507,
        y: 126,
      },
    ],
    [
      687,
      {
        creatureId: 58,
        effectType: "weaponEffect",
        weaponEffectType: "projectile",
        projectileType: "pebble",
        weaponType: "slingshot",
        direction: "right",
        angle: 7,
        x: 449,
        y: 106,
      },
    ],
    [
      724,
      {
        creatureId: 62,
        effectType: "weaponEffect",
        weaponEffectType: "projectile",
        projectileType: "pebble",
        weaponType: "slingshot",
        direction: "right",
        angle: -2,
        x: 419,
        y: 110,
      },
    ],
  ]),
  objects: new Map([
    [
      17,
      {
        team: "red",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: true,
        towerName: "topRight",
        width: 24,
        height: 24,
        durability: 985,
        maxDurability: 1000,
        x: 468,
        y: 108,
      },
    ],
    [
      18,
      {
        team: "red",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: true,
        towerName: "bottomRight",
        width: 24,
        height: 24,
        durability: 1000,
        maxDurability: 1000,
        x: 468,
        y: 276,
      },
    ],
    [
      19,
      {
        team: "blue",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: true,
        towerName: "bottomLeft",
        width: 24,
        height: 24,
        durability: 714,
        maxDurability: 1000,
        x: 172,
        y: 276,
      },
    ],
    [
      20,
      {
        team: "blue",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: false,
        towerName: "topLeft",
        width: 24,
        height: 24,
        durability: 505,
        maxDurability: 1000,
        x: 172,
        y: 108,
      },
    ],
  ]),
  players: new Map([
    [
      "yvVTRec9OYBq",
      {
        name: "Lime Moth",
        team: "blue",
        randomSlots: [],
        restrictionZones: "",
      },
    ],
    [
      "iSfj9vIZlNIJK0BvpgW9iiEJErzdWVP8",
      {
        name: "Aseph",
        team: "red",
        hero: 63,
        cents: 260,
        deck: {
          card1: "cleric",
          card2: "goblinCatapult",
          card3: "golem",
          card4: "offenseUp",
          card5: "elf",
          card6: "halfling",
          card7: "goblin",
          card8: "healthPotion",
        },
        randomSlots: [],
        hand: {
          slot1: "halfling",
          slot2: "healthPotion",
          slot3: "goblin",
          slot4: "goblinCatapult",
        },
        skills: {
          slot1: {
            type: "spiritGuardians",
            inUse: true,
            cooldown: 0,
            cooldownTotal: 0,
          },
          slot2: {
            type: "wordOfPain",
            inUse: false,
            cooldown: 1194,
            cooldownTotal: 4400,
          },
          slot3: {
            type: "healingWord",
            inUse: false,
            cooldown: 1194,
            cooldownTotal: 4400,
          },
        },
        restrictionZones: "blueBase,bottomLeft,topLeft",
      },
    ],
  ]),
  spectators: new Map(),
  info: {
    timeElapsed: 66,
  },
};

const encodedDiff = GameState.encodeDiff(state1, state2);
console.log("encodedDiff", encodedDiff);
// Uint8Array(276)

const decodedDiff = GameState.decodeDiff(state1, encodedDiff);
assert(GameState.equals(decodedDiff, state2));
