import assert from "assert";
import { GameState } from "./output5.ts";
import { NO_DIFF } from "../helpers.ts";

const state1: GameState = {
  creatures: new Map([
    [
      64,
      {
        team: "blue",
        hero: false,
        creatureType: "golem",
        health: 85,
        maxHealth: 600,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "stomp",
        useDirection: "downRight",
        takingDamage: false,
        frozen: false,
        x: 234,
        y: 281,
        dead: false,
      },
    ],
    [
      76,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 225,
        y: 237,
        dead: false,
      },
    ],
    [
      67,
      {
        team: "red",
        hero: false,
        creatureType: "human",
        equippedItemType: "longsword",
        health: 0,
        maxHealth: 110,
        visible: true,
        facing: "upLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 245,
        y: 281,
        dead: true,
      },
    ],
    [
      56,
      {
        team: "blue",
        hero: false,
        creatureType: "goblin",
        equippedItemType: "spear",
        health: 21,
        maxHealth: 75,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        takingDamage: true,
        frozen: false,
        x: 450,
        y: 112,
        dead: false,
      },
    ],
    [
      74,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 232,
        y: 233,
        dead: false,
      },
    ],
    [
      54,
      {
        team: "blue",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 197,
        y: 260,
        dead: false,
      },
    ],
    [
      53,
      {
        team: "blue",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 197,
        y: 264,
        dead: false,
      },
    ],
    [
      75,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 228,
        y: 235,
        dead: false,
      },
    ],
    [
      51,
      {
        team: "blue",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 192,
        y: 260,
        dead: false,
      },
    ],
    [
      50,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 211,
        y: 290,
        dead: false,
      },
    ],
    [
      49,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 209,
        y: 294,
        dead: false,
      },
    ],
    [
      48,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        using: "attack",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 210,
        y: 293,
        dead: false,
      },
    ],
    [
      47,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 28,
        maxHealth: 70,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 212,
        y: 286,
        dead: false,
      },
    ],
    [
      46,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 28,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 212,
        y: 261,
        dead: false,
      },
    ],
    [
      65,
      {
        team: "red",
        hero: false,
        creatureType: "human",
        equippedItemType: "longsword",
        health: 0,
        maxHealth: 110,
        visible: true,
        facing: "upLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 245,
        y: 277,
        dead: true,
      },
    ],
    [
      73,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 230,
        y: 230,
        dead: false,
      },
    ],
    [
      52,
      {
        team: "blue",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 198,
        y: 242,
        dead: false,
      },
    ],
    [
      77,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 219,
        y: 238,
        dead: false,
      },
    ],
    [
      59,
      {
        team: "blue",
        hero: false,
        creatureType: "goblin",
        equippedItemType: "spear",
        health: 75,
        maxHealth: 75,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 451,
        y: 108,
        dead: false,
      },
    ],
    [
      66,
      {
        team: "red",
        hero: false,
        creatureType: "human",
        equippedItemType: "longsword",
        health: 0,
        maxHealth: 110,
        visible: true,
        facing: "upLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 246,
        y: 277,
        dead: true,
      },
    ],
    [
      69,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "left",
        takingDamage: false,
        frozen: false,
        x: 312,
        y: 272,
        dead: false,
      },
    ],
    [
      72,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 308,
        y: 268,
        dead: false,
      },
    ],
    [
      70,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "left",
        takingDamage: false,
        frozen: false,
        x: 311,
        y: 265,
        dead: false,
      },
    ],
    [
      71,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 308,
        y: 264,
        dead: false,
      },
    ],
    [
      35,
      {
        team: "red",
        hero: false,
        creatureType: "necromancer",
        health: 200,
        maxHealth: 200,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 276,
        y: 272,
        dead: false,
      },
    ],
    [
      34,
      {
        team: "red",
        hero: false,
        creatureType: "towerGuard",
        equippedItemType: "towerGuardBow",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 468,
        y: 276,
        dead: false,
      },
    ],
    [
      33,
      {
        team: "blue",
        hero: false,
        creatureType: "towerGuard",
        equippedItemType: "towerGuardBow",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 172,
        y: 276,
        dead: false,
      },
    ],
    [
      32,
      {
        team: "red",
        hero: false,
        creatureType: "towerGuard",
        equippedItemType: "towerGuardBow",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 468,
        y: 108,
        dead: false,
      },
    ],
    [
      31,
      {
        team: "blue",
        hero: false,
        creatureType: "towerGuard",
        equippedItemType: "towerGuardBow",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 172,
        y: 108,
        dead: false,
      },
    ],
    [
      30,
      {
        team: "red",
        hero: false,
        creatureType: "kingRed",
        equippedItemType: "kingSword",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "upRight",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 603,
        y: 185,
        dead: false,
      },
    ],
    [
      29,
      {
        team: "blue",
        hero: false,
        creatureType: "kingBlue",
        equippedItemType: "kingSword",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "upLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 38,
        y: 185,
        dead: false,
      },
    ],
  ]),
  items: new Map(),
  effects: new Map([
    [
      271,
      {
        creatureId: 70,
        effectType: "weaponEffect",
        weaponEffectType: "projectile",
        projectileType: "arrow",
        weaponType: "bow",
        direction: "left",
        angle: 169,
        x: 291,
        y: 269,
      },
    ],
    [
      720,
      {
        creatureId: 69,
        effectType: "weaponEffect",
        weaponEffectType: "projectile",
        projectileType: "arrow",
        weaponType: "bow",
        direction: "left",
        angle: 173,
        x: 282,
        y: 275,
      },
    ],
  ]),
  objects: new Map([
    [
      40,
      {
        team: "blue",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: true,
        towerName: "topLeft",
        width: 24,
        height: 24,
        durability: 1000,
        maxDurability: 1000,
        x: 172,
        y: 108,
      },
    ],
    [
      39,
      {
        team: "blue",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: true,
        towerName: "bottomLeft",
        width: 24,
        height: 24,
        durability: 244,
        maxDurability: 1000,
        x: 172,
        y: 276,
      },
    ],
    [
      38,
      {
        team: "red",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: true,
        towerName: "bottomRight",
        width: 24,
        height: 24,
        durability: 1000,
        maxDurability: 1000,
        x: 468,
        y: 276,
      },
    ],
    [
      37,
      {
        team: "red",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: true,
        towerName: "topRight",
        width: 24,
        height: 24,
        durability: 769,
        maxDurability: 1000,
        x: 468,
        y: 108,
      },
    ],
  ]),
  players: new Map([
    [
      "iSfj9vIZlNIJK0BvpgW9iiEJErzdWVP8",
      {
        name: "Aseph",
        team: "blue",
        randomSlots: [],
        cents: 290,
        deck: {
          card1: "cleric",
          card2: "goblinCatapult",
          card3: "golem",
          card4: "offenseUp",
          card5: "elf",
          card6: "halfling",
          card7: "goblin",
          card8: "healthPotion",
        },
        hand: {
          slot1: "goblinCatapult",
          slot2: "cleric",
          slot3: "offenseUp",
          slot4: "healthPotion",
        },
        skills: {},
        restrictionZones: "bottomRight,redBase,topRight",
      },
    ],
    [
      "NJiPu7eKpwEs",
      {
        name: "Few Finch",
        team: "red",
        randomSlots: [],
        restrictionZones: "",
      },
    ],
  ]),
  spectators: new Map(),
  info: {
    timeElapsed: 38,
  },
  debugBodies: [],
};

const encoded = GameState.encode(state1).toBuffer();
console.log("encoded", encoded);
// Uint8Array(953)

const decoded = GameState.decode(encoded);
assert.equal(GameState.computeDiff(state1, decoded), NO_DIFF);

const state2: GameState = {
  creatures: new Map([
    [
      64,
      {
        team: "blue",
        hero: false,
        creatureType: "golem",
        health: 85,
        maxHealth: 600,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "stomp",
        useDirection: "downRight",
        takingDamage: false,
        frozen: false,
        x: 234,
        y: 281,
        dead: false,
      },
    ],
    [
      76,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 226,
        y: 238,
        dead: false,
      },
    ],
    [
      67,
      {
        team: "red",
        hero: false,
        creatureType: "human",
        equippedItemType: "longsword",
        health: 0,
        maxHealth: 110,
        visible: true,
        facing: "upLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 245,
        y: 281,
        dead: true,
      },
    ],
    [
      56,
      {
        team: "blue",
        hero: false,
        creatureType: "goblin",
        equippedItemType: "spear",
        health: 21,
        maxHealth: 75,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 450,
        y: 112,
        dead: false,
      },
    ],
    [
      74,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "downRight",
        takingDamage: false,
        frozen: false,
        x: 232,
        y: 233,
        dead: false,
      },
    ],
    [
      54,
      {
        team: "blue",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 197,
        y: 260,
        dead: false,
      },
    ],
    [
      53,
      {
        team: "blue",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "right",
        takingDamage: false,
        frozen: false,
        x: 197,
        y: 264,
        dead: false,
      },
    ],
    [
      75,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "downRight",
        takingDamage: false,
        frozen: false,
        x: 228,
        y: 235,
        dead: false,
      },
    ],
    [
      51,
      {
        team: "blue",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 193,
        y: 260,
        dead: false,
      },
    ],
    [
      50,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 212,
        y: 290,
        dead: false,
      },
    ],
    [
      49,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 210,
        y: 294,
        dead: false,
      },
    ],
    [
      48,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 209,
        y: 292,
        dead: false,
      },
    ],
    [
      47,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 28,
        maxHealth: 70,
        visible: true,
        facing: "upRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 213,
        y: 286,
        dead: false,
      },
    ],
    [
      46,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 28,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 213,
        y: 261,
        dead: false,
      },
    ],
    [
      65,
      {
        team: "red",
        hero: false,
        creatureType: "human",
        equippedItemType: "longsword",
        health: 0,
        maxHealth: 110,
        visible: true,
        facing: "upLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 245,
        y: 277,
        dead: true,
      },
    ],
    [
      73,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 230,
        y: 229,
        dead: false,
      },
    ],
    [
      52,
      {
        team: "blue",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 199,
        y: 242,
        dead: false,
      },
    ],
    [
      77,
      {
        team: "blue",
        hero: false,
        creatureType: "halfling",
        equippedItemType: "slingshot",
        health: 70,
        maxHealth: 70,
        visible: true,
        facing: "downRight",
        moving: true,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 220,
        y: 239,
        dead: false,
      },
    ],
    [
      59,
      {
        team: "blue",
        hero: false,
        creatureType: "goblin",
        equippedItemType: "spear",
        health: 75,
        maxHealth: 75,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 451,
        y: 108,
        dead: false,
      },
    ],
    [
      66,
      {
        team: "red",
        hero: false,
        creatureType: "human",
        equippedItemType: "longsword",
        health: 0,
        maxHealth: 110,
        visible: true,
        facing: "upLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 246,
        y: 277,
        dead: true,
      },
    ],
    [
      69,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "left",
        takingDamage: false,
        frozen: false,
        x: 312,
        y: 272,
        dead: false,
      },
    ],
    [
      72,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 308,
        y: 268,
        dead: false,
      },
    ],
    [
      70,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        using: "attack",
        useDirection: "left",
        takingDamage: false,
        frozen: false,
        x: 311,
        y: 265,
        dead: false,
      },
    ],
    [
      71,
      {
        team: "red",
        hero: false,
        creatureType: "elf",
        equippedItemType: "bow",
        health: 100,
        maxHealth: 100,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 307,
        y: 264,
        dead: false,
      },
    ],
    [
      35,
      {
        team: "red",
        hero: false,
        creatureType: "necromancer",
        health: 200,
        maxHealth: 200,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 276,
        y: 272,
        dead: false,
      },
    ],
    [
      34,
      {
        team: "red",
        hero: false,
        creatureType: "towerGuard",
        equippedItemType: "towerGuardBow",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 468,
        y: 276,
        dead: false,
      },
    ],
    [
      33,
      {
        team: "blue",
        hero: false,
        creatureType: "towerGuard",
        equippedItemType: "towerGuardBow",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 172,
        y: 276,
        dead: false,
      },
    ],
    [
      32,
      {
        team: "red",
        hero: false,
        creatureType: "towerGuard",
        equippedItemType: "towerGuardBow",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "downLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 468,
        y: 108,
        dead: false,
      },
    ],
    [
      31,
      {
        team: "blue",
        hero: false,
        creatureType: "towerGuard",
        equippedItemType: "towerGuardBow",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "downRight",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 172,
        y: 108,
        dead: false,
      },
    ],
    [
      30,
      {
        team: "red",
        hero: false,
        creatureType: "kingRed",
        equippedItemType: "kingSword",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "upRight",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 603,
        y: 185,
        dead: false,
      },
    ],
    [
      29,
      {
        team: "blue",
        hero: false,
        creatureType: "kingBlue",
        equippedItemType: "kingSword",
        health: 1000,
        maxHealth: 1000,
        visible: true,
        facing: "upLeft",
        moving: false,
        moveType: "walk",
        takingDamage: false,
        frozen: false,
        x: 38,
        y: 185,
        dead: false,
      },
    ],
  ]),
  items: new Map(),
  effects: new Map([
    [
      720,
      {
        creatureId: 69,
        effectType: "weaponEffect",
        weaponEffectType: "projectile",
        projectileType: "arrow",
        weaponType: "bow",
        direction: "left",
        angle: 173,
        x: 272,
        y: 276,
      },
    ],
    [
      721,
      {
        creatureId: 70,
        effectType: "weaponEffect",
        weaponEffectType: "projectile",
        projectileType: "arrow",
        weaponType: "bow",
        direction: "left",
        angle: 169,
        x: 281,
        y: 271,
      },
    ],
  ]),
  objects: new Map([
    [
      40,
      {
        team: "blue",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: true,
        towerName: "topLeft",
        width: 24,
        height: 24,
        durability: 1000,
        maxDurability: 1000,
        x: 172,
        y: 108,
      },
    ],
    [
      39,
      {
        team: "blue",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: true,
        towerName: "bottomLeft",
        width: 24,
        height: 24,
        durability: 244,
        maxDurability: 1000,
        x: 172,
        y: 276,
      },
    ],
    [
      38,
      {
        team: "red",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: true,
        towerName: "bottomRight",
        width: 24,
        height: 24,
        durability: 1000,
        maxDurability: 1000,
        x: 468,
        y: 276,
      },
    ],
    [
      37,
      {
        team: "red",
        objectType: "destructible",
        destructibleObjectType: "tower",
        active: true,
        towerName: "topRight",
        width: 24,
        height: 24,
        durability: 769,
        maxDurability: 1000,
        x: 468,
        y: 108,
      },
    ],
  ]),
  players: new Map([
    [
      "iSfj9vIZlNIJK0BvpgW9iiEJErzdWVP8",
      {
        name: "Aseph",
        team: "blue",
        randomSlots: [],
        cents: 290,
        deck: {
          card1: "cleric",
          card2: "goblinCatapult",
          card3: "golem",
          card4: "offenseUp",
          card5: "elf",
          card6: "halfling",
          card7: "goblin",
          card8: "healthPotion",
        },
        hand: {
          slot1: "goblinCatapult",
          slot2: "cleric",
          slot3: "offenseUp",
          slot4: "healthPotion",
        },
        skills: {},
        restrictionZones: "bottomRight,redBase,topRight",
      },
    ],
    [
      "NJiPu7eKpwEs",
      {
        name: "Few Finch",
        team: "red",
        randomSlots: [],
        restrictionZones: "",
      },
    ],
  ]),
  spectators: new Map(),
  info: {
    timeElapsed: 38,
  },
  debugBodies: [],
};

const diff = GameState.computeDiff(state1, state2);
console.log(
  "diff",
  JSON.stringify(diff, (k, v) => (v instanceof Map || v instanceof Set ? [...v] : v), 2),
);
// console.log("diff", util.inspect(diff, { depth: null, colors: true }));
if (diff === NO_DIFF) {
  assert.fail("diff === NO_DIFF");
}
const encodedDiff = GameState.encodeDiff(diff).toBuffer();
console.log("encodedDiff", encodedDiff);
// Uint8Array(169)

const decodedDiff = GameState.decodeDiff(encodedDiff);
const applied = GameState.applyDiff(state1, decodedDiff);
assert.equal(GameState.computeDiff(applied, state2), NO_DIFF);
