import { Type, NamedType, isPrimitiveOrEnum } from "@hpx7/delta-pack";

export function codegenCsharp(
  schema: Record<string, Type>,
  namespace: string = "Generated",
): string {
  const ctx = createContext(schema, namespace);
  return renderSchema(ctx);
}

// ============ Context ============

interface GeneratorContext {
  schema: Record<string, Type>;
  namespace: string;
  currentTypeName: string;
  variantToUnion: Map<string, string>;
}

function createContext(
  schema: Record<string, Type>,
  namespace: string,
): GeneratorContext {
  const variantToUnion = new Map<string, string>();
  for (const [name, type] of Object.entries(schema)) {
    if (type.type === "union") {
      for (const option of type.options) {
        variantToUnion.set(option.name!, name);
      }
    }
  }
  return { schema, namespace, currentTypeName: "", variantToUnion };
}

// ============ Utilities ============

function ifElseChain<T>(
  items: readonly T[],
  render: (item: T, i: number, prefix: string) => string,
): string {
  return items
    .map((item, i) => render(item, i, i > 0 ? "else " : ""))
    .join("\n");
}

function toPascalCase(str: string): string {
  return str ? str.charAt(0).toUpperCase() + str.slice(1) : str;
}

function toCamelCase(str: string): string {
  return str ? str.charAt(0).toLowerCase() + str.slice(1) : str;
}

function qualify(ctx: GeneratorContext, name: string): string {
  return `${ctx.namespace}.${name}`;
}

// ============ Main Renderer ============

function renderSchema(ctx: GeneratorContext): string {
  const enums: string[] = [];
  const classes: string[] = [];

  for (const [name, type] of Object.entries(ctx.schema)) {
    ctx.currentTypeName = name;
    if (type.type === "enum") {
      enums.push(renderEnum(name, type.options));
    } else if (type.type === "object") {
      classes.push(
        renderObject(ctx, name, type.properties, ctx.variantToUnion.get(name)),
      );
    } else if (type.type === "union") {
      classes.push(renderUnion(ctx, name, type.options, type.numBits));
    }
  }

  return `// Auto-generated by DeltaPack - do not edit
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Nodes;
using DeltaPack;

namespace ${ctx.namespace}
{
${[...enums, ...classes].join("\n\n")}
}
`;
}

// ============ Enum Renderer ============

function renderEnum(name: string, options: readonly string[]): string {
  const values = options
    .map((opt, i) => `        ${toPascalCase(opt)} = ${i}`)
    .join(",\n");
  return `    public enum ${name}
    {
${values}
    }`;
}

// ============ Object Renderer ============

function renderObject(
  ctx: GeneratorContext,
  name: string,
  properties: Record<string, Type>,
  baseClass?: string,
): string {
  const props = Object.entries(properties);
  const isVariant = baseClass != null;
  const mod = isVariant ? "new " : "";
  const p = (fn: (n: string, t: Type) => string) =>
    props.map(([n, t]) => fn(n, t)).join("\n");

  const propLines = p((n, t) => {
    const csType = renderType(ctx, t, n);
    const needsDefault =
      t.type !== "boolean" &&
      t.type !== "optional" &&
      t.type !== "int" &&
      t.type !== "float";
    return needsDefault
      ? `        public ${csType} ${toPascalCase(n)} { get; set; } = ${renderDefault(ctx, t, n)};`
      : `        public ${csType} ${toPascalCase(n)} { get; set; }`;
  });

  const fromJsonBody = p((n, t) => {
    const pc = toPascalCase(n);
    return t.type === "optional"
      ? `                ${pc} = json.TryGetProperty("${n}", out var ${n}El) ? ${renderFromJson(ctx, t, n, `${n}El`)} : null,`
      : `                ${pc} = ${renderFromJson(ctx, t, n, `json.GetProperty("${n}")`)},`;
  });

  const toJsonBody = p((n, t) => {
    const pc = toPascalCase(n);
    if (t.type === "optional") {
      const check = isValueType(t.value)
        ? `obj.${pc}.HasValue`
        : `obj.${pc} != null`;
      return `            if (${check}) result["${n}"] = ${renderToJson(ctx, t, n, `obj.${pc}`)};`;
    }
    return `            result["${n}"] = ${renderToJson(ctx, t, n, `obj.${pc}`)};`;
  });

  const cloneBody = p((n, t) => {
    const pc = toPascalCase(n);
    return `                ${pc} = ${renderClone(ctx, t, n, `obj.${pc}`)},`;
  });

  const equalsBody = props
    .map(([n, t]) => {
      const pc = toPascalCase(n);
      return renderEquals(ctx, t, n, `a.${pc}`, `b.${pc}`);
    })
    .join(" &&\n                ");

  const encodeBody = p(
    (n, t) =>
      `            ${renderEncode(ctx, t, n, `obj.${toPascalCase(n)}`)};`,
  );

  const encodeDiffBody = p((n, t) => {
    const pc = toPascalCase(n);
    const enc = renderEncodeDiff(ctx, t, n, `a.${pc}`, `b.${pc}`);
    const suffix = enc.trimStart().startsWith("{") ? "" : ";";
    return `            ${enc}${suffix}`;
  });

  const decodeBody = p(
    (n, t) =>
      `                ${toPascalCase(n)} = ${renderDecode(ctx, t, n)},`,
  );

  const decodeDiffBody = p((n, t) => {
    const pc = toPascalCase(n);
    return `                ${pc} = ${renderDecodeDiff(ctx, t, n, `obj.${pc}`)},`;
  });

  const classDecl = baseClass
    ? `    public class ${name} : ${baseClass}`
    : `    public class ${name}`;
  const typeOverride = isVariant
    ? `        public override string Type => "${name}";\n\n`
    : "";

  return `${classDecl}
    {
${typeOverride}${propLines}

        public static ${mod}${name} Default() => new ${name}();

        public static ${mod}${name} FromJson(JsonElement json)
        {
            return new ${name}
            {
${fromJsonBody}
            };
        }

        public static JsonObject ToJson(${name} obj)
        {
            var result = new JsonObject();
${toJsonBody}
            return result;
        }

        public static ${name} Clone(${name} obj)
        {
            return new ${name}
            {
${cloneBody}
            };
        }

        public static bool Equals(${name} a, ${name} b)
        {
            return ${equalsBody || "true"};
        }

        public static byte[] Encode(${name} obj)
        {
            var encoder = new Encoder();
            EncodeInternal(obj, encoder);
            return encoder.ToBuffer();
        }

        internal static void EncodeInternal(${name} obj, Encoder encoder)
        {
${encodeBody}
        }

        public static byte[] EncodeDiff(${name} a, ${name} b)
        {
            var encoder = new Encoder();
            EncodeDiffInternal(a, b, encoder);
            return encoder.ToBuffer();
        }

        internal static void EncodeDiffInternal(${name} a, ${name} b, Encoder encoder)
        {
            var changed = !Equals(a, b);
            encoder.PushBoolean(changed);
            if (!changed) return;
${encodeDiffBody}
        }

        public static ${mod}${name} Decode(byte[] buf)
        {
            var decoder = new Decoder(buf);
            return DecodeInternal(decoder);
        }

        internal static ${mod}${name} DecodeInternal(Decoder decoder)
        {
            return new ${name}
            {
${decodeBody}
            };
        }

        public static ${name} DecodeDiff(${name} obj, byte[] diff)
        {
            var decoder = new Decoder(diff);
            return DecodeDiffInternal(obj, decoder);
        }

        internal static ${name} DecodeDiffInternal(${name} obj, Decoder decoder)
        {
            var changed = decoder.NextBoolean();
            if (!changed) return obj;
            return new ${name}
            {
${decodeDiffBody}
            };
        }
    }`;
}

// ============ Union Renderer ============

function renderUnion(
  ctx: GeneratorContext,
  name: string,
  options: readonly NamedType[],
  numBits: number,
): string {
  const first = options[0]!.name;

  const variantNames = options.map((opt) => `"${opt.name}"`).join(", ");
  const fromJsonCases = ifElseChain(
    options,
    (opt, _, p) =>
      `                ${p}if (typeName == "${opt.name}") return ${opt.name}.FromJson(val);`,
  );
  const fromJsonPropCases = ifElseChain(
    options,
    (opt, _, p) =>
      `                ${p}if (typeName == "${opt.name}") return ${opt.name}.FromJson(valProp);`,
  );
  const toJsonCases = ifElseChain(options, (opt, _, p) => {
    const v = toCamelCase(opt.name!);
    return `            ${p}if (obj is ${opt.name} ${v}) return new JsonObject { ["${opt.name}"] = ${opt.name}.ToJson(${v}) };`;
  });
  const cloneCases = ifElseChain(options, (opt, _, p) => {
    const v = toCamelCase(opt.name!);
    return `            ${p}if (obj is ${opt.name} ${v}) return ${opt.name}.Clone(${v});`;
  });
  const equalsCases = ifElseChain(options, (opt, _, p) => {
    const v = toCamelCase(opt.name!);
    return `            ${p}if (a is ${opt.name} ${v}A && b is ${opt.name} ${v}B) return ${opt.name}.Equals(${v}A, ${v}B);`;
  });
  const encodeCases = ifElseChain(options, (opt, i, p) => {
    const v = toCamelCase(opt.name!);
    return `            ${p}if (obj is ${opt.name} ${v})
            {
                encoder.PushEnum(${i}, ${numBits});
                ${opt.name}.EncodeInternal(${v}, encoder);
            }`;
  });
  const encodeDiffCases = ifElseChain(options, (opt, i, p) => {
    const v = toCamelCase(opt.name!);
    return `            ${p}if (b is ${opt.name} ${v}B)
            {
                if (a is ${opt.name} ${v}A)
                {
                    ${opt.name}.EncodeDiffInternal(${v}A, ${v}B, encoder);
                }
                else
                {
                    encoder.PushEnum(${i}, ${numBits});
                    ${opt.name}.EncodeInternal(${v}B, encoder);
                }
            }`;
  });
  const decodeCases = ifElseChain(
    options,
    (opt, i, p) =>
      `            ${p}if (type == ${i}) return ${opt.name}.DecodeInternal(decoder);`,
  );
  const decodeDiffSameCases = ifElseChain(options, (opt, _, p) => {
    const v = toCamelCase(opt.name!);
    return `                ${p}if (obj is ${opt.name} ${v}) return ${opt.name}.DecodeDiffInternal(${v}, decoder);`;
  });
  const decodeDiffNewCases = ifElseChain(
    options,
    (opt, i, p) =>
      `                ${p}if (type == ${i}) return ${opt.name}.DecodeInternal(decoder);`,
  );

  return `    public abstract class ${name}
    {
        public abstract string Type { get; }

        public static ${name} Default() => ${first}.Default();

        public static ${name} FromJson(JsonElement json)
        {
            if (json.TryGetProperty("type", out var typeEl) && json.TryGetProperty("val", out var val))
            {
                var typeName = JsonHelpers.FindVariant(typeEl.GetString()!, ${variantNames});
${fromJsonCases}
                throw new InvalidOperationException($"Unknown ${name} type: {typeEl.GetString()}");
            }
            var prop = json.EnumerateObject().FirstOrDefault();
            if (prop.Value.ValueKind != JsonValueKind.Undefined)
            {
                var typeName = JsonHelpers.FindVariant(prop.Name, ${variantNames});
                var valProp = prop.Value;
${fromJsonPropCases}
            }
            throw new InvalidOperationException("Invalid ${name} format");
        }

        public static JsonObject ToJson(${name} obj)
        {
${toJsonCases}
            throw new InvalidOperationException($"Unknown ${name} type: {obj.Type}");
        }

        public static ${name} Clone(${name} obj)
        {
${cloneCases}
            throw new InvalidOperationException($"Unknown ${name} type: {obj.Type}");
        }

        public static bool Equals(${name} a, ${name} b)
        {
            if (a.Type != b.Type) return false;
${equalsCases}
            return false;
        }

        public static byte[] Encode(${name} obj)
        {
            var encoder = new Encoder();
            EncodeInternal(obj, encoder);
            return encoder.ToBuffer();
        }

        internal static void EncodeInternal(${name} obj, Encoder encoder)
        {
${encodeCases}
        }

        public static byte[] EncodeDiff(${name} a, ${name} b)
        {
            var encoder = new Encoder();
            EncodeDiffInternal(a, b, encoder);
            return encoder.ToBuffer();
        }

        internal static void EncodeDiffInternal(${name} a, ${name} b, Encoder encoder)
        {
            encoder.PushBoolean(a.Type == b.Type);
${encodeDiffCases}
        }

        public static ${name} Decode(byte[] buf)
        {
            var decoder = new Decoder(buf);
            return DecodeInternal(decoder);
        }

        internal static ${name} DecodeInternal(Decoder decoder)
        {
            var type = decoder.NextEnum(${numBits});
${decodeCases}
            throw new InvalidOperationException("Invalid ${name} union");
        }

        public static ${name} DecodeDiff(${name} obj, byte[] diff)
        {
            var decoder = new Decoder(diff);
            return DecodeDiffInternal(obj, decoder);
        }

        internal static ${name} DecodeDiffInternal(${name} obj, Decoder decoder)
        {
            var isSameType = decoder.NextBoolean();
            if (isSameType)
            {
${decodeDiffSameCases}
                throw new InvalidOperationException("Invalid ${name} diff");
            }
            else
            {
                var type = decoder.NextEnum(${numBits});
${decodeDiffNewCases}
                throw new InvalidOperationException("Invalid ${name} diff");
            }
        }
    }`;
}

// ============ Type Helpers ============

function isValueType(type: Type): boolean {
  if (type.type === "reference") return isValueType(type.ref);
  return (
    type.type === "int" ||
    type.type === "float" ||
    type.type === "boolean" ||
    type.type === "enum"
  );
}

function renderType(ctx: GeneratorContext, type: Type, name: string): string {
  switch (type.type) {
    case "string":
      return "string";
    case "int":
      return "long";
    case "float":
      return "float";
    case "boolean":
      return "bool";
    case "enum":
      return type.name!;
    case "array":
      return `List<${renderType(ctx, type.value, name)}>`;
    case "optional":
      return `${renderType(ctx, type.value, name)}?`;
    case "record":
      return `Dictionary<${renderType(ctx, type.key, name)}, ${renderType(ctx, type.value, name)}>`;
    case "reference":
      return type.ref.name!;
    case "self-reference":
      return ctx.currentTypeName;
    default:
      throw new Error(`Unexpected type in renderType: ${type.type}`);
  }
}

function renderDefault(
  ctx: GeneratorContext,
  type: Type,
  name: string,
): string {
  switch (type.type) {
    case "string":
      return '""';
    case "int":
      return "0";
    case "float":
      return "0f";
    case "boolean":
      return "false";
    case "enum":
      return `${type.name!}.${toPascalCase(type.options[0]!)}`;
    case "array":
      return `new List<${renderType(ctx, type.value, name)}>()`;
    case "optional":
      return "null";
    case "record":
      return `new Dictionary<${renderType(ctx, type.key, name)}, ${renderType(ctx, type.value, name)}>()`;
    case "reference":
      return renderDefault(ctx, type.ref, type.ref.name!);
    case "self-reference":
      return `${qualify(ctx, ctx.currentTypeName)}.Default()`;
    default:
      return `${qualify(ctx, name)}.Default()`;
  }
}

function renderFromJson(
  ctx: GeneratorContext,
  type: Type,
  name: string,
  key: string,
): string {
  switch (type.type) {
    case "string":
      return `JsonHelpers.ParseString(${key})`;
    case "int":
      return `${key}.GetInt64()`;
    case "float":
      return `${key}.GetSingle()`;
    case "boolean":
      return `JsonHelpers.ParseBoolean(${key})`;
    case "enum":
      return `JsonHelpers.ParseEnum<${type.name!}>(${key})`;
    case "array":
      return `${key}.EnumerateArray().Select(x => ${renderFromJson(ctx, type.value, name, "x")}).ToList()`;
    case "optional":
      return `JsonHelpers.IsNullOrEmpty(${key}) ? null : ${renderFromJson(ctx, type.value, name, key)}`;
    case "record":
      return type.key.type === "string"
        ? `${key}.EnumerateObject().ToDictionary(p => p.Name, p => ${renderFromJson(ctx, type.value, name, "p.Value")})`
        : `${key}.EnumerateObject().ToDictionary(p => long.Parse(p.Name), p => ${renderFromJson(ctx, type.value, name, "p.Value")})`;
    case "reference":
      return renderFromJson(ctx, type.ref, type.ref.name!, key);
    case "self-reference":
      return `${qualify(ctx, ctx.currentTypeName)}.FromJson(${key})`;
    default:
      return `${qualify(ctx, name)}.FromJson(${key})`;
  }
}

function renderToJson(
  ctx: GeneratorContext,
  type: Type,
  name: string,
  key: string,
): string {
  switch (type.type) {
    case "string":
    case "int":
    case "float":
    case "boolean":
      return key;
    case "enum":
      return `${key}.ToString()`;
    case "array":
      return `new JsonArray(${key}.Select(x => (JsonNode?)${renderToJson(ctx, type.value, name, "x")}).ToArray())`;
    case "optional":
      return renderToJson(ctx, type.value, name, key);
    case "record":
      return type.key.type === "string"
        ? `new JsonObject(${key}.Select(kvp => new KeyValuePair<string, JsonNode?>(kvp.Key, ${renderToJson(ctx, type.value, name, "kvp.Value")})))`
        : `new JsonObject(${key}.Select(kvp => new KeyValuePair<string, JsonNode?>(kvp.Key.ToString(), ${renderToJson(ctx, type.value, name, "kvp.Value")})))`;
    case "reference":
      return renderToJson(ctx, type.ref, type.ref.name!, key);
    case "self-reference":
      return `${qualify(ctx, ctx.currentTypeName)}.ToJson(${key})`;
    case "union":
      return `${qualify(ctx, type.name!)}.ToJson(${key})`;
    default:
      return `${qualify(ctx, name)}.ToJson(${key})`;
  }
}

function renderClone(
  ctx: GeneratorContext,
  type: Type,
  name: string,
  key: string,
): string {
  switch (type.type) {
    case "string":
    case "int":
    case "float":
    case "boolean":
    case "enum":
      return key;
    case "array":
      return isPrimitiveOrEnum(type.value)
        ? `new List<${renderType(ctx, type.value, name)}>(${key})`
        : `${key}.Select(x => ${renderClone(ctx, type.value, name, "x")}).ToList()`;
    case "optional":
      return isPrimitiveOrEnum(type.value)
        ? key
        : `${key} != null ? ${renderClone(ctx, type.value, name, key)} : null`;
    case "record":
      return isPrimitiveOrEnum(type.value)
        ? `new Dictionary<${renderType(ctx, type.key, name)}, ${renderType(ctx, type.value, name)}>(${key})`
        : `${key}.ToDictionary(kvp => kvp.Key, kvp => ${renderClone(ctx, type.value, name, "kvp.Value")})`;
    case "reference":
      return renderClone(ctx, type.ref, type.ref.name!, key);
    case "self-reference":
      return `${qualify(ctx, ctx.currentTypeName)}.Clone(${key})`;
    case "union":
      return `${qualify(ctx, type.name!)}.Clone(${key})`;
    default:
      return `${qualify(ctx, name)}.Clone(${key})`;
  }
}

function renderEquals(
  ctx: GeneratorContext,
  type: Type,
  name: string,
  a: string,
  b: string,
): string {
  switch (type.type) {
    case "string":
    case "int":
    case "boolean":
    case "enum":
      return `${a} == ${b}`;
    case "float":
      return type.precision
        ? `Math.Abs(${a} - ${b}) < ${type.precision / 2}f`
        : `${a} == ${b}`;
    case "array":
      return `${a}.Count == ${b}.Count && ${a}.Zip(${b}).All(pair => ${renderEquals(ctx, type.value, name, "pair.First", "pair.Second")})`;
    case "optional":
      return isValueType(type.value) || isPrimitiveOrEnum(type.value)
        ? `${a} == ${b}`
        : `(${a} == null && ${b} == null || ${a} != null && ${b} != null && ${renderEquals(ctx, type.value, name, a, b)})`;
    case "record":
      return `${a}.Count == ${b}.Count && ${a}.All(kvp => ${b}.TryGetValue(kvp.Key, out var v) && ${renderEquals(ctx, type.value, name, "kvp.Value", "v")})`;
    case "reference":
      return renderEquals(ctx, type.ref, type.ref.name!, a, b);
    case "self-reference":
      return `${qualify(ctx, ctx.currentTypeName)}.Equals(${a}, ${b})`;
    case "union":
      return `${qualify(ctx, type.name!)}.Equals(${a}, ${b})`;
    default:
      return `${qualify(ctx, name)}.Equals(${a}, ${b})`;
  }
}

function renderEncode(
  ctx: GeneratorContext,
  type: Type,
  name: string,
  key: string,
): string {
  switch (type.type) {
    case "string":
      return `encoder.PushString(${key})`;
    case "int":
      return type.min != null && type.min >= 0
        ? `encoder.PushBoundedInt(${key}, ${type.min})`
        : `encoder.PushInt(${key})`;
    case "float":
      return type.precision
        ? `encoder.PushFloatQuantized(${key}, ${type.precision}f)`
        : `encoder.PushFloat(${key})`;
    case "boolean":
      return `encoder.PushBoolean(${key})`;
    case "enum":
      return `encoder.PushEnum((int)${key}, ${type.numBits})`;
    case "array":
      return `encoder.PushArray(${key}, x => ${renderEncode(ctx, type.value, name, "x")})`;
    case "optional":
      if (isValueType(type.value)) {
        return `encoder.PushBoolean(${key}.HasValue);\n            if (${key}.HasValue) ${renderEncode(ctx, type.value, name, `${key}.Value`)}`;
      }
      return `encoder.PushOptional(${key}, x => ${renderEncode(ctx, type.value, name, "x")})`;
    case "record":
      return `encoder.PushRecord(${key}, x => ${renderEncode(ctx, type.key, name, "x")}, x => ${renderEncode(ctx, type.value, name, "x")})`;
    case "reference":
      return renderEncode(ctx, type.ref, type.ref.name!, key);
    case "self-reference":
      return `${qualify(ctx, ctx.currentTypeName)}.EncodeInternal(${key}, encoder)`;
    case "union":
      return `${qualify(ctx, type.name!)}.EncodeInternal(${key}, encoder)`;
    default:
      return `${qualify(ctx, name)}.EncodeInternal(${key}, encoder)`;
  }
}

function renderDecode(ctx: GeneratorContext, type: Type, name: string): string {
  switch (type.type) {
    case "string":
      return `decoder.NextString()`;
    case "int":
      return type.min != null && type.min >= 0
        ? `decoder.NextBoundedInt(${type.min})`
        : `decoder.NextInt()`;
    case "float":
      return type.precision
        ? `decoder.NextFloatQuantized(${type.precision}f)`
        : `decoder.NextFloat()`;
    case "boolean":
      return `decoder.NextBoolean()`;
    case "enum":
      return `(${type.name!})decoder.NextEnum(${type.numBits})`;
    case "array":
      return `decoder.NextArray(() => ${renderDecode(ctx, type.value, name)})`;
    case "optional":
      if (isValueType(type.value)) {
        const t = renderType(ctx, type.value, name);
        const inner =
          type.value.type === "reference" ? type.value.ref : type.value;
        if (inner.type === "enum") {
          return `decoder.NextBoolean() ? (${t}?)decoder.NextEnum(${inner.numBits}) : null`;
        }
        return `decoder.NextBoolean() ? (${t}?)${renderDecode(ctx, type.value, name)} : null`;
      }
      return `decoder.NextOptional(() => ${renderDecode(ctx, type.value, name)})`;
    case "record":
      return `decoder.NextRecord(() => ${renderDecode(ctx, type.key, name)}, () => ${renderDecode(ctx, type.value, name)})`;
    case "reference":
      return renderDecode(ctx, type.ref, type.ref.name!);
    case "self-reference":
      return `${qualify(ctx, ctx.currentTypeName)}.DecodeInternal(decoder)`;
    case "union":
      return `${qualify(ctx, type.name!)}.DecodeInternal(decoder)`;
    default:
      return `${qualify(ctx, name)}.DecodeInternal(decoder)`;
  }
}

function renderEncodeDiff(
  ctx: GeneratorContext,
  type: Type,
  name: string,
  a: string,
  b: string,
): string {
  switch (type.type) {
    case "string":
      return `encoder.PushStringDiff(${a}, ${b})`;
    case "int":
      return type.min != null && type.min >= 0
        ? `encoder.PushBoundedIntDiff(${a}, ${b}, ${type.min})`
        : `encoder.PushIntDiff(${a}, ${b})`;
    case "float":
      return type.precision
        ? `encoder.PushFloatQuantizedDiff(${a}, ${b}, ${type.precision}f)`
        : `encoder.PushFloatDiff(${a}, ${b})`;
    case "boolean":
      return `encoder.PushBooleanDiff(${a}, ${b})`;
    case "enum":
      return `encoder.PushEnumDiff((int)${a}, (int)${b}, ${type.numBits})`;
    case "array": {
      const t = renderType(ctx, type.value, name);
      return `encoder.PushArrayDiff<${t}>(${a}, ${b}, (x, y) => ${renderEquals(ctx, type.value, name, "x", "y")}, x => ${renderEncode(ctx, type.value, name, "x")}, (x, y) => ${renderEncodeDiff(ctx, type.value, name, "x", "y")})`;
    }
    case "optional": {
      const t = renderType(ctx, type.value, name);
      if (isValueType(type.value)) {
        return `{
                var eq = ${a} == ${b};
                encoder.PushBoolean(!eq);
                if (!eq)
                {
                    encoder.PushBoolean(${b}.HasValue);
                    if (${b}.HasValue) ${renderEncode(ctx, type.value, name, `${b}.Value`)};
                }
            }`;
      }
      return isPrimitiveOrEnum(type.value)
        ? `encoder.PushOptionalDiffPrimitive<${t}>(${a}, ${b}, x => ${renderEncode(ctx, type.value, name, "x")})`
        : `encoder.PushOptionalDiff<${t}>(${a}, ${b}, x => ${renderEncode(ctx, type.value, name, "x")}, (x, y) => ${renderEncodeDiff(ctx, type.value, name, "x", "y")})`;
    }
    case "record": {
      const kt = renderType(ctx, type.key, name);
      const vt = renderType(ctx, type.value, name);
      return `encoder.PushRecordDiff<${kt}, ${vt}>(${a}, ${b}, (x, y) => ${renderEquals(ctx, type.value, name, "x", "y")}, x => ${renderEncode(ctx, type.key, name, "x")}, x => ${renderEncode(ctx, type.value, name, "x")}, (x, y) => ${renderEncodeDiff(ctx, type.value, name, "x", "y")})`;
    }
    case "reference":
      return renderEncodeDiff(ctx, type.ref, type.ref.name!, a, b);
    case "self-reference":
      return `${qualify(ctx, ctx.currentTypeName)}.EncodeDiffInternal(${a}, ${b}, encoder)`;
    case "union":
      return `${qualify(ctx, type.name!)}.EncodeDiffInternal(${a}, ${b}, encoder)`;
    default:
      return `${qualify(ctx, name)}.EncodeDiffInternal(${a}, ${b}, encoder)`;
  }
}

function renderDecodeDiff(
  ctx: GeneratorContext,
  type: Type,
  name: string,
  key: string,
): string {
  switch (type.type) {
    case "string":
      return `decoder.NextStringDiff(${key})`;
    case "int":
      return type.min != null && type.min >= 0
        ? `decoder.NextBoundedIntDiff(${key}, ${type.min})`
        : `decoder.NextIntDiff(${key})`;
    case "float":
      return type.precision
        ? `decoder.NextFloatQuantizedDiff(${key}, ${type.precision}f)`
        : `decoder.NextFloatDiff(${key})`;
    case "boolean":
      return `decoder.NextBooleanDiff(${key})`;
    case "enum":
      return `(${type.name!})decoder.NextEnumDiff((int)${key}, ${type.numBits})`;
    case "array": {
      const t = renderType(ctx, type.value, name);
      return `decoder.NextArrayDiff<${t}>(${key}, () => ${renderDecode(ctx, type.value, name)}, x => ${renderDecodeDiff(ctx, type.value, name, "x")})`;
    }
    case "optional": {
      const t = renderType(ctx, type.value, name);
      if (isValueType(type.value)) {
        const inner =
          type.value.type === "reference" ? type.value.ref : type.value;
        if (inner.type === "enum") {
          return `decoder.NextBoolean() ? (decoder.NextBoolean() ? (${t}?)decoder.NextEnum(${inner.numBits}) : null) : ${key}`;
        }
        return `decoder.NextBoolean() ? (decoder.NextBoolean() ? (${t}?)${renderDecode(ctx, type.value, name)} : null) : ${key}`;
      }
      return isPrimitiveOrEnum(type.value)
        ? `decoder.NextOptionalDiffPrimitive<${t}>(${key}, () => ${renderDecode(ctx, type.value, name)})`
        : `decoder.NextOptionalDiff<${t}>(${key}, () => ${renderDecode(ctx, type.value, name)}, x => ${renderDecodeDiff(ctx, type.value, name, "x")})`;
    }
    case "record": {
      const kt = renderType(ctx, type.key, name);
      const vt = renderType(ctx, type.value, name);
      return `decoder.NextRecordDiff<${kt}, ${vt}>(${key}, () => ${renderDecode(ctx, type.key, name)}, () => ${renderDecode(ctx, type.value, name)}, x => ${renderDecodeDiff(ctx, type.value, name, "x")})`;
    }
    case "reference":
      return renderDecodeDiff(ctx, type.ref, type.ref.name!, key);
    case "self-reference":
      return `${qualify(ctx, ctx.currentTypeName)}.DecodeDiffInternal(${key}, decoder)`;
    case "union":
      return `${qualify(ctx, type.name!)}.DecodeDiffInternal(${key}, decoder)`;
    default:
      return `${qualify(ctx, name)}.DecodeDiffInternal(${key}, decoder)`;
  }
}
