import { Type } from "@hpx7/delta-pack";
import { dispatch } from "./visitor.js";

/**
 * Emits minimal C# skeletons annotated with `[DeltaPack]`. The `DeltaPack.SourceGenerator`
 * Roslyn source generator fills in `Encode`/`Decode`/`EncodeDiff`/`DecodeDiff`/`Equals`/
 * `Clone`/`Default`/`FromJson`/`ToJson` at the consumer's compile time.
 *
 * Keeping CLI output minimal means a single source of truth for the emission logic
 * (the C# generator) — no drift between this TypeScript emitter and the Roslyn one.
 */
export function codegenCsharp(
  schema: Record<string, Type>,
  namespace: string = "Generated",
): string {
  const ctx = createContext(schema, namespace);
  return renderSchema(ctx);
}

// ============ Context ============

interface GeneratorContext {
  schema: Record<string, Type>;
  namespace: string;
  currentTypeName: string;
  variantToUnion: Map<string, string>;
}

function createContext(
  schema: Record<string, Type>,
  namespace: string,
): GeneratorContext {
  const variantToUnion = new Map<string, string>();
  for (const [name, type] of Object.entries(schema)) {
    if (type.type === "union") {
      for (const option of type.options) {
        variantToUnion.set(option.name!, name);
      }
    }
  }
  return {
    schema,
    namespace,
    currentTypeName: "",
    variantToUnion,
  };
}

// ============ Utilities ============

function toPascalCase(str: string): string {
  return str ? str.charAt(0).toUpperCase() + str.slice(1) : str;
}

// ============ Main Renderer ============

function renderSchema(ctx: GeneratorContext): string {
  const parts: string[] = [];

  for (const [name, type] of Object.entries(ctx.schema)) {
    ctx.currentTypeName = name;
    if (type.type === "enum") {
      parts.push(renderEnum(name, type.options));
    } else if (type.type === "object") {
      parts.push(
        renderObject(ctx, name, type.properties, ctx.variantToUnion.get(name)),
      );
    } else if (type.type === "union") {
      parts.push(renderUnion(name, type.options.map((o) => o.name!)));
    }
  }

  return `// Auto-generated by DeltaPack - do not edit
using DeltaPack;

namespace ${ctx.namespace}
{
${parts.join("\n\n")}
}
`;
}

// ============ Enum Renderer ============

function renderEnum(name: string, options: readonly string[]): string {
  const values = options
    .map((opt, i) => `        ${toPascalCase(opt)} = ${i}`)
    .join(",\n");
  return `    public enum ${name}
    {
${values}
    }`;
}

// ============ Object Renderer ============

function renderObject(
  ctx: GeneratorContext,
  name: string,
  properties: Record<string, Type>,
  baseClass?: string,
): string {
  const props = Object.entries(properties);
  const propLines = props
    .map(([n, t]) => renderProperty(ctx, n, t))
    .join("\n");

  const classHeader = baseClass
    ? `    public partial class ${name} : ${baseClass}`
    : `    public partial class ${name}`;

  return `    [DeltaPack]
${classHeader}
    {
${propLines}
    }`;
}

// ============ Union Renderer ============

function renderUnion(name: string, variants: readonly string[]): string {
  const variantTypes = variants.map((v) => `typeof(${v})`).join(", ");
  return `    [DeltaPack]
    [DeltaPackUnion(${variantTypes})]
    public abstract partial class ${name} { }`;
}

// ============ Property Renderer ============

function renderProperty(
  ctx: GeneratorContext,
  name: string,
  type: Type,
): string {
  const pc = toPascalCase(name);
  const csType = renderType(ctx, type);
  const attrs = renderAttributes(type);
  const attrPrefix = attrs ? `${attrs} ` : "";
  const init = renderInitializer(ctx, type);
  const trailer = init ? ` = ${init};` : "";
  return `        ${attrPrefix}public ${csType} ${pc} { get; set; }${trailer}`;
}

// ============ Attribute Renderer ============

/**
 * Emits `[DeltaPackRange(...)]` / `[DeltaPackPrecision(...)]` on a property where the
 * schema captures a min/max or precision that the source generator needs to pick the
 * right encoding strategy.
 */
function renderAttributes(type: Type): string {
  // Attributes apply to the property itself — unwrap optional so `int(min=0, max=5)?`
  // still carries its `[DeltaPackRange(0,5)]`.
  const inner = type.type === "optional" ? type.value : type;
  if (inner.type === "int") {
    const hasMin = inner.min !== undefined;
    const hasMax = inner.max !== undefined;
    if (hasMin && hasMax) return `[DeltaPackRange(${inner.min}, ${inner.max})]`;
    if (hasMin) return `[DeltaPackRange(${inner.min})]`;
    return "";
  }
  if (inner.type === "float" && inner.precision !== undefined && inner.precision !== 0) {
    return `[DeltaPackPrecision(${inner.precision}f)]`;
  }
  return "";
}

// ============ Type & Initializer Renderers ============

function renderType(ctx: GeneratorContext, type: Type): string {
  return dispatch(type, {
    string: () => "string",
    int: () => "long",
    float: () => "float",
    boolean: () => "bool",
    enum: (t) => t.name,
    array: (t) =>
      `System.Collections.Generic.List<${renderType(ctx, t.value)}>`,
    optional: (t) => `${renderType(ctx, t.value)}?`,
    record: (t) =>
      `DeltaPack.OrderedDict<${renderType(ctx, t.key)}, ${renderType(ctx, t.value)}>`,
    selfReference: () => ctx.currentTypeName,
    object: (t) => t.name,
    union: (t) => t.name,
  });
}

/**
 * Returns the RHS initializer for a property, or the empty string when no
 * initializer is needed (the language default is fine for that type).
 */
function renderInitializer(ctx: GeneratorContext, type: Type): string {
  return dispatch(type, {
    string: () => '""',
    int: () => "",
    float: () => "",
    boolean: () => "",
    enum: () => "",
    array: (t) =>
      `new System.Collections.Generic.List<${renderType(ctx, t.value)}>()`,
    optional: () => "",
    record: (t) =>
      `new DeltaPack.OrderedDict<${renderType(ctx, t.key)}, ${renderType(ctx, t.value)}>()`,
    selfReference: () => `${ctx.currentTypeName}.Default()`,
    object: (t) => `${t.name}.Default()`,
    union: (t) => `${t.name}.Default()`,
  });
}
