import { Type, NamedType, isPrimitiveOrEnum } from "@hpx7/delta-pack";
import { dispatch } from "./visitor.js";
import { intStrategy, floatStrategy, DiffContext } from "./strategy.js";

export function codegenRust(
  schema: Record<string, Type>,
  _namespace?: string,
): string {
  const ctx = createContext(schema);
  return renderSchema(ctx);
}

// ============ Context ============

interface GeneratorContext {
  schema: Record<string, Type>;
  currentTypeName: string;
  variantToUnion: Map<string, string>;
}

function createContext(schema: Record<string, Type>): GeneratorContext {
  const variantToUnion = new Map<string, string>();
  for (const [name, type] of Object.entries(schema)) {
    if (type.type === "union") {
      for (const option of type.options) {
        variantToUnion.set(option.name!, name);
      }
    }
  }
  return {
    schema,
    currentTypeName: "",
    variantToUnion,
  };
}

// ============ Utilities ============

// Rust reserved keywords that need escaping
const RUST_KEYWORDS = new Set([
  "as",
  "break",
  "const",
  "continue",
  "crate",
  "else",
  "enum",
  "extern",
  "false",
  "fn",
  "for",
  "if",
  "impl",
  "in",
  "let",
  "loop",
  "match",
  "mod",
  "move",
  "mut",
  "pub",
  "ref",
  "return",
  "self",
  "Self",
  "static",
  "struct",
  "super",
  "trait",
  "true",
  "type",
  "unsafe",
  "use",
  "where",
  "while",
  "async",
  "await",
  "dyn",
  "bool",
  "str",
  "f32",
  "f64",
]);

function toSnakeCase(str: string): string {
  return str
    .replace(/([A-Z])/g, "_$1")
    .toLowerCase()
    .replace(/^_/, "");
}

// Returns [rustFieldName, needsRename] - adds _ suffix for keywords
function toRustFieldName(str: string): [string, boolean] {
  const snake = toSnakeCase(str);
  if (RUST_KEYWORDS.has(snake)) {
    return [`${snake}_`, true];
  }
  return [snake, false];
}

function toPascalCase(str: string): string {
  return str ? str.charAt(0).toUpperCase() + str.slice(1) : str;
}

// ============ Main Renderer ============

function renderSchema(ctx: GeneratorContext): string {
  const enums: string[] = [];
  const structs: string[] = [];

  for (const [name, type] of Object.entries(ctx.schema)) {
    ctx.currentTypeName = name;
    if (type.type === "enum") {
      enums.push(renderEnum(name, type.options, type.numBits));
    } else if (type.type === "object") {
      structs.push(
        renderObject(ctx, name, type.properties, ctx.variantToUnion.get(name)),
      );
    } else if (type.type === "union") {
      structs.push(renderUnion(ctx, name, type.options, type.numBits));
    }
  }

  return `// Auto-generated by DeltaPack - do not edit
#![allow(dead_code, unused_imports, unused_variables, clippy::all)]

use delta_pack::{Decoder, Encoder};
use serde::{Deserialize, Serialize};
use delta_pack::IndexMap;

${[...enums, ...structs].join("\n\n")}
`;
}

// ============ Enum Renderer ============

function renderEnum(
  name: string,
  options: readonly string[],
  numBits: number,
): string {
  // Add serde rename if PascalCase differs from original (preserves JSON interop)
  const variants = options
    .map((opt) => {
      const pascal = toPascalCase(opt);
      if (pascal !== opt) {
        return `    #[serde(rename = "${opt}")]\n    ${pascal},`;
      }
      return `    ${pascal},`;
    })
    .join("\n");

  const fromU32Cases = options
    .map((opt, i) => `            ${i} => ${name}::${toPascalCase(opt)},`)
    .join("\n");

  const toU32Cases = options
    .map((opt, i) => `            ${name}::${toPascalCase(opt)} => ${i},`)
    .join("\n");

  return `#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ${name} {
${variants}
}

impl ${name} {
    pub const NUM_BITS: u8 = ${numBits};

    pub fn from_u32(val: u32) -> Self {
        match val {
${fromU32Cases}
            _ => panic!("Invalid ${name} value: {}", val),
        }
    }

    pub fn to_u32(self) -> u32 {
        match self {
${toU32Cases}
        }
    }
}

impl Default for ${name} {
    fn default() -> Self {
        ${name}::${toPascalCase(options[0]!)}
    }
}`;
}

// ============ Object Renderer ============

function renderObject(
  ctx: GeneratorContext,
  name: string,
  properties: Record<string, Type>,
  _baseUnion?: string,
): string {
  const props = Object.entries(properties);

  // Pre-compute rust field names with rename info
  // Add serde rename if the snake_case name differs from original (handles camelCase and keywords)
  const fieldInfo = props.map(([n, t]) => {
    const [rustName, isKeyword] = toRustFieldName(n);
    const needsRename = isKeyword || rustName !== n;
    return { originalName: n, rustName, needsRename, type: t };
  });

  const p = (fn: (info: (typeof fieldInfo)[0]) => string) =>
    fieldInfo.map(fn).join("\n");

  const fieldLines = p((info) => {
    const rustType = renderType(ctx, info.type);
    const renameAttr = info.needsRename
      ? `    #[serde(rename = "${info.originalName}")]\n`
      : "";
    return `${renameAttr}    pub ${info.rustName}: ${rustType},`;
  });

  const defaultLines = p((info) => {
    return `            ${info.rustName}: ${renderDefault(ctx, info.type)},`;
  });

  const cloneLines = p((info) => {
    const field = `self.${info.rustName}`;
    return `            ${info.rustName}: ${renderClone(ctx, info.type, field)},`;
  });

  const equalsExprs = fieldInfo.map((info) => {
    return renderEquals(
      ctx,
      info.type,
      `self.${info.rustName}`,
      `other.${info.rustName}`,
    );
  });
  const equalsLines =
    equalsExprs.length <= 1
      ? equalsExprs.join("")
      : equalsExprs.join("\n            && ");

  const encodeLines = p((info) => {
    const field = `self.${info.rustName}`;
    return `        ${renderEncode(ctx, info.type, field)};`;
  });

  const encodeDiffLines = p((info) => {
    if (hasOwnChangeBit(info.type)) {
      // Type handles its own change bit
      return `        ${renderEncodeDiff(ctx, info.type, `a.${info.rustName}`, `b.${info.rustName}`)};`;
    } else {
      // Use push_field_diff helper
      const eq = renderEquals(ctx, info.type, "x", "y", true);
      const diffCb = renderEncodeDiffCallback(ctx, info.type);
      return `        encoder.push_field_diff(&a.${info.rustName}, &b.${info.rustName}, |x, y| ${eq}, ${diffCb});`;
    }
  });

  const decodeLines = p((info) => {
    return `            ${info.rustName}: ${renderDecode(ctx, info.type)},`;
  });

  const decodeDiffLines = p((info) => {
    const field = `obj.${info.rustName}`;
    if (hasOwnChangeBit(info.type)) {
      // Type handles its own change bit
      return `            ${info.rustName}: ${renderDecodeDiff(ctx, info.type, field)},`;
    } else {
      // Use next_field_diff helper
      const diffCb = renderDecodeDiffCallback(ctx, info.type);
      return `            ${info.rustName}: decoder.next_field_diff(&${field}, ${diffCb}),`;
    }
  });

  return `#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ${name} {
${fieldLines}
}

impl Default for ${name} {
    fn default() -> Self {
        Self {
${defaultLines}
        }
    }
}

impl ${name} {
    pub fn equals(&self, other: &Self) -> bool {
        ${equalsLines || "true"}
    }

    pub fn encode(&self) -> Vec<u8> {
        Encoder::encode(|encoder| {
            self.encode_into(encoder);
            encoder.finish()
        })
    }

    pub fn encode_into(&self, encoder: &mut Encoder) {
${encodeLines}
    }

    pub fn encode_diff(a: &Self, b: &Self) -> Vec<u8> {
        Encoder::encode(|encoder| {
            encoder.push_object_diff(a, b, |x, y| x.equals(y), |enc| {
                Self::encode_diff_into(a, b, enc);
            });
            encoder.finish()
        })
    }

    pub fn encode_diff_into(a: &Self, b: &Self, encoder: &mut Encoder) {
${encodeDiffLines}
    }

    pub fn decode(buf: &[u8]) -> Self {
        Decoder::decode(buf, |decoder| Self::decode_from(decoder))
    }

    pub fn decode_from(decoder: &mut Decoder) -> Self {
        Self {
${decodeLines}
        }
    }

    pub fn decode_diff(obj: &Self, diff: &[u8]) -> Self {
        Decoder::decode(diff, |decoder| {
            decoder.next_object_diff(obj, |dec| Self::decode_diff_from(obj, dec))
        })
    }

    pub fn decode_diff_from(obj: &Self, decoder: &mut Decoder) -> Self {
        Self {
${decodeDiffLines}
        }
    }
}`;
}

// ============ Union Renderer ============

function renderUnion(
  ctx: GeneratorContext,
  name: string,
  options: readonly NamedType[],
  numBits: number,
): string {
  const variants = options
    .map((opt) => `    ${opt.name}(${opt.name}),`)
    .join("\n");

  const defaultVariant = options[0]!.name;

  const cloneCases = options
    .map(
      (opt) =>
        `            ${name}::${opt.name}(v) => ${name}::${opt.name}(v.clone()),`,
    )
    .join("\n");

  const equalsCases = options
    .map(
      (opt) =>
        `            (${name}::${opt.name}(a), ${name}::${opt.name}(b)) => a.equals(b),`,
    )
    .join("\n");

  const encodeCases = options
    .map(
      (opt, i) =>
        `            ${name}::${opt.name}(v) => {
                encoder.push_enum(${i}, ${numBits});
                v.encode_into(encoder);
            }`,
    )
    .join("\n");

  const encodeDiffCases = options
    .map(
      (opt, i) =>
        `            ${name}::${opt.name}(b_val) => {
                if let ${name}::${opt.name}(a_val) = a {
                    ${opt.name}::encode_diff_into(a_val, b_val, encoder);
                } else {
                    encoder.push_enum(${i}, ${numBits});
                    b_val.encode_into(encoder);
                }
            }`,
    )
    .join("\n");

  const decodeCases = options
    .map(
      (opt, i) =>
        `            ${i} => ${name}::${opt.name}(${opt.name}::decode_from(decoder)),`,
    )
    .join("\n");

  const decodeDiffSameCases = options
    .map(
      (opt) =>
        `                ${name}::${opt.name}(v) => ${name}::${opt.name}(${opt.name}::decode_diff_from(v, decoder)),`,
    )
    .join("\n");

  const decodeDiffNewCases = options
    .map(
      (opt, i) =>
        `                ${i} => ${name}::${opt.name}(${opt.name}::decode_from(decoder)),`,
    )
    .join("\n");

  return `#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum ${name} {
${variants}
}

impl Default for ${name} {
    fn default() -> Self {
        ${name}::${defaultVariant}(${defaultVariant}::default())
    }
}

impl ${name} {
    pub fn equals(&self, other: &Self) -> bool {
        match (self, other) {
${equalsCases}
            _ => false,
        }
    }

    pub fn encode(&self) -> Vec<u8> {
        Encoder::encode(|encoder| {
            self.encode_into(encoder);
            encoder.finish()
        })
    }

    pub fn encode_into(&self, encoder: &mut Encoder) {
        match self {
${encodeCases}
        }
    }

    pub fn encode_diff(a: &Self, b: &Self) -> Vec<u8> {
        Encoder::encode(|encoder| {
            Self::encode_diff_into(a, b, encoder);
            encoder.finish()
        })
    }

    pub fn encode_diff_into(a: &Self, b: &Self, encoder: &mut Encoder) {
        let same_type = std::mem::discriminant(a) == std::mem::discriminant(b);
        encoder.push_boolean(same_type);
        match b {
${encodeDiffCases}
        }
    }

    pub fn decode(buf: &[u8]) -> Self {
        Decoder::decode(buf, |decoder| Self::decode_from(decoder))
    }

    pub fn decode_from(decoder: &mut Decoder) -> Self {
        let variant = decoder.next_enum(${numBits});
        match variant {
${decodeCases}
            _ => panic!("Invalid ${name} variant: {}", variant),
        }
    }

    pub fn decode_diff(obj: &Self, diff: &[u8]) -> Self {
        Decoder::decode(diff, |decoder| Self::decode_diff_from(obj, decoder))
    }

    pub fn decode_diff_from(obj: &Self, decoder: &mut Decoder) -> Self {
        let same_type = decoder.next_boolean();
        if same_type {
            match obj {
${decodeDiffSameCases}
            }
        } else {
            let variant = decoder.next_enum(${numBits});
            match variant {
${decodeDiffNewCases}
                _ => panic!("Invalid ${name} variant: {}", variant),
            }
        }
    }
}`;
}

// ============ Type Helpers ============

// Cast `expr - offset` into a u32 for bit-packed enum encoding.
function intBitOffsetRs(expr: string, offset: number): string {
  if (offset === 0) return `${expr} as u32`;
  const minExpr = offset < 0 ? `(${offset})` : `${offset}`;
  return `(${expr} - ${minExpr}) as u32`;
}

// Cast a bit-packed enum decode result back to the storage type and re-add offset.
function intBitDecodeRs(
  decodeExpr: string,
  offset: number,
  isSigned: boolean,
): string {
  const target = isSigned ? "i64" : "u64";
  if (offset === 0) return `${decodeExpr} as ${target}`;
  const minExpr = offset < 0 ? `(${offset})` : `${offset}`;
  return `${decodeExpr} as ${target} + ${minExpr}`;
}

// Types that handle their own change bit in diff encoding
function hasOwnChangeBit(type: Type): boolean {
  if (type.type === "boolean") return true;
  if (type.type === "reference") {
    return type.ref.type === "union";
  }
  return false;
}

// Rust `Copy` types — passed by value in direct form, destructured in closures.
// Controls the direct-form `&` prefix and the closure's binder shape.
function isCopyType(type: Type): boolean {
  const inner = type.type === "reference" ? type.ref : type;
  return (
    inner.type === "int" ||
    inner.type === "float" ||
    inner.type === "boolean" ||
    inner.type === "enum"
  );
}

// Direct-form arg: `expr` for Copy types, `&expr` for reference types.
function directDiffArg(expr: string, type: Type): string {
  return isCopyType(type) ? expr : `&${expr}`;
}

// Closure binder for diff callbacks. `singleArg` is for decode-diff (`|dec, a|`);
// the encode-diff form takes two args (`|enc, a, b|`).
function callbackDiffBinder(type: Type, singleArg: boolean): string {
  if (singleArg) return isCopyType(type) ? "&a" : "a";
  return isCopyType(type) ? "&a, &b" : "a, b";
}

function renderType(ctx: GeneratorContext, type: Type): string {
  return dispatch(type, {
    string: () => "String",
    int: (t) => (t.min != null && t.min >= 0 ? "u64" : "i64"),
    float: () => "f32",
    boolean: () => "bool",
    enum: (t) => t.name,
    array: (t) => `Vec<${renderType(ctx, t.value)}>`,
    optional: (t) => `Option<${renderType(ctx, t.value)}>`,
    record: (t) =>
      `IndexMap<${renderType(ctx, t.key)}, ${renderType(ctx, t.value)}>`,
    selfReference: () => `Box<${ctx.currentTypeName}>`,
    object: (t) => t.name,
    union: (t) => t.name,
  });
}

function renderDefault(ctx: GeneratorContext, type: Type): string {
  return dispatch(type, {
    string: () => "String::new()",
    int: () => "0",
    float: () => "0.0",
    boolean: () => "false",
    enum: (t) => `${t.name}::default()`,
    array: () => "Vec::new()",
    optional: () => "None",
    record: () => "IndexMap::new()",
    selfReference: () => `Box::new(${ctx.currentTypeName}::default())`,
    object: (t) => `${t.name}::default()`,
    union: (t) => `${t.name}::default()`,
  });
}

function renderClone(ctx: GeneratorContext, type: Type, key: string): string {
  return dispatch(type, {
    string: () => `${key}.clone()`,
    int: () => key,
    float: () => key,
    boolean: () => key,
    enum: () => key,
    array: (t) =>
      isPrimitiveOrEnum(t.value)
        ? `${key}.clone()`
        : `${key}.iter().map(|x| ${renderClone(ctx, t.value, "x.clone()")}).collect()`,
    optional: (t) =>
      isPrimitiveOrEnum(t.value)
        ? `${key}.clone()`
        : `${key}.as_ref().map(|x| ${renderClone(ctx, t.value, "x.clone()")})`,
    record: (t) =>
      isPrimitiveOrEnum(t.value)
        ? `${key}.clone()`
        : `${key}.iter().map(|(k, v)| (k.clone(), ${renderClone(ctx, t.value, "v.clone()")})).collect()`,
    selfReference: () => `Box::new((**${key}).clone())`,
    object: () => `${key}.clone()`,
    union: () => `${key}.clone()`,
  });
}

// inClosure: when true, a and b are already references (closure params)
function renderEquals(
  ctx: GeneratorContext,
  type: Type,
  a: string,
  b: string,
  inClosure = false,
): string {
  return dispatch(type, {
    string: () => `${a} == ${b}`,
    int: () => `${a} == ${b}`,
    boolean: () => `${a} == ${b}`,
    enum: () => `${a} == ${b}`,
    float: (t) => {
      const s = floatStrategy(t);
      // In closures, a and b are references that need dereferencing for float comparison
      const aExpr = inClosure ? `*${a}` : a;
      const bExpr = inClosure ? `*${b}` : b;
      return s.kind === "quantized"
        ? `delta_pack::equals_float_quantized(${aExpr}, ${bExpr}, ${s.precision}_f32)`
        : `delta_pack::equals_float(${aExpr}, ${bExpr})`;
    },
    array: (t) =>
      isPrimitiveOrEnum(t.value)
        ? `${a} == ${b}`
        : `delta_pack::equals_array(&${a}, &${b}, |x, y| ${renderEquals(ctx, t.value, "x", "y", true)})`,
    optional: (t) =>
      isPrimitiveOrEnum(t.value)
        ? `${a} == ${b}`
        : `delta_pack::equals_optional(&${a}, &${b}, |x, y| ${renderEquals(ctx, t.value, "x", "y", true)})`,
    record: (t) =>
      isPrimitiveOrEnum(t.value)
        ? `${a} == ${b}`
        : `delta_pack::equals_record(&${a}, &${b}, |x, y| ${renderEquals(ctx, t.value, "x", "y", true)})`,
    selfReference: () =>
      inClosure ? `${a}.equals(${b})` : `${a}.equals(&${b})`,
    // In closures, params are already refs; in struct fields, need explicit &
    object: () => (inClosure ? `${a}.equals(${b})` : `${a}.equals(&${b})`),
    union: () => (inClosure ? `${a}.equals(${b})` : `${a}.equals(&${b})`),
  });
}

// Generate a closure for encoding a single value (used by push_array, push_optional, push_record)
function renderEncodeCallback(ctx: GeneratorContext, type: Type): string {
  return dispatch(type, {
    string: () => `|enc, item| enc.push_string(item)`,
    int: (t) => {
      const s = intStrategy(t);
      if (s.kind === "packed") {
        return `|enc, &item| enc.push_enum(${intBitOffsetRs("item", s.offset)}, ${s.numBits})`;
      }
      if (s.kind === "unsigned") {
        return s.min === 0
          ? `|enc, &item| enc.push_uint(item)`
          : `|enc, &item| enc.push_uint(item - ${s.min})`;
      }
      return `|enc, &item| enc.push_int(item)`;
    },
    float: (t) => {
      const s = floatStrategy(t);
      return s.kind === "quantized"
        ? `|enc, &item| enc.push_float_quantized(item, ${s.precision}_f32)`
        : `|enc, &item| enc.push_float(item)`;
    },
    boolean: () => `|enc, &item| enc.push_boolean(item)`,
    enum: (t) => `|enc, &item| enc.push_enum(item.to_u32(), ${t.numBits})`,
    array: (t) => {
      const innerEncode = renderEncodeCallback(ctx, t.value);
      return `|enc, item| enc.push_array(item, ${innerEncode})`;
    },
    optional: (t) => {
      const innerEncode = renderEncodeCallback(ctx, t.value);
      return `|enc, item| enc.push_optional(item, ${innerEncode})`;
    },
    record: (t) => {
      const keyEncode = renderEncodeCallback(ctx, t.key);
      const valEncode = renderEncodeCallback(ctx, t.value);
      return `|enc, item| enc.push_record(item, ${keyEncode}, ${valEncode})`;
    },
    selfReference: () => `|enc, item| item.encode_into(enc)`,
    object: () => `|enc, item| item.encode_into(enc)`,
    union: () => `|enc, item| item.encode_into(enc)`,
  });
}

function renderEncode(ctx: GeneratorContext, type: Type, key: string): string {
  return dispatch(type, {
    string: () => `encoder.push_string(&${key})`,
    int: (t) => {
      const s = intStrategy(t);
      if (s.kind === "packed") {
        return `encoder.push_enum(${intBitOffsetRs(key, s.offset)}, ${s.numBits})`;
      }
      if (s.kind === "unsigned") {
        return s.min === 0
          ? `encoder.push_uint(${key})`
          : `encoder.push_uint(${key} - ${s.min})`;
      }
      return `encoder.push_int(${key})`;
    },
    float: (t) => {
      const s = floatStrategy(t);
      return s.kind === "quantized"
        ? `encoder.push_float_quantized(${key}, ${s.precision}_f32)`
        : `encoder.push_float(${key})`;
    },
    boolean: () => `encoder.push_boolean(${key})`,
    enum: (t) => `encoder.push_enum(${key}.to_u32(), ${t.numBits})`,
    array: (t) => {
      const innerEncode = renderEncodeCallback(ctx, t.value);
      return `encoder.push_array(&${key}, ${innerEncode})`;
    },
    optional: (t) => {
      const innerEncode = renderEncodeCallback(ctx, t.value);
      return `encoder.push_optional(&${key}, ${innerEncode})`;
    },
    record: (t) => {
      const keyEncode = renderEncodeCallback(ctx, t.key);
      const valEncode = renderEncodeCallback(ctx, t.value);
      return `encoder.push_record(&${key}, ${keyEncode}, ${valEncode})`;
    },
    selfReference: () => `${key}.encode_into(encoder)`,
    object: () => `${key}.encode_into(encoder)`,
    union: () => `${key}.encode_into(encoder)`,
  });
}

// Generate a closure for decoding a single value (used by next_array, next_optional, next_record)
function renderDecodeCallback(ctx: GeneratorContext, type: Type): string {
  return dispatch(type, {
    string: () => `|dec| dec.next_string()`,
    int: (t) => {
      const s = intStrategy(t);
      if (s.kind === "packed") {
        const signed = s.offset < 0;
        return `|dec| ${intBitDecodeRs(`dec.next_enum(${s.numBits})`, s.offset, signed)}`;
      }
      if (s.kind === "unsigned") {
        return s.min === 0
          ? `|dec| dec.next_uint()`
          : `|dec| dec.next_uint() + ${s.min}`;
      }
      return `|dec| dec.next_int()`;
    },
    float: (t) => {
      const s = floatStrategy(t);
      return s.kind === "quantized"
        ? `|dec| dec.next_float_quantized(${s.precision}_f32)`
        : `|dec| dec.next_float()`;
    },
    boolean: () => `|dec| dec.next_boolean()`,
    enum: (t) => `|dec| ${t.name}::from_u32(dec.next_enum(${t.numBits}))`,
    array: (t) => {
      const innerDecode = renderDecodeCallback(ctx, t.value);
      return `|dec| dec.next_array(${innerDecode})`;
    },
    optional: (t) => {
      const innerDecode = renderDecodeCallback(ctx, t.value);
      return `|dec| dec.next_optional(${innerDecode})`;
    },
    record: (t) => {
      const keyDecode = renderDecodeCallback(ctx, t.key);
      const valDecode = renderDecodeCallback(ctx, t.value);
      return `|dec| dec.next_record(${keyDecode}, ${valDecode})`;
    },
    // Self-references are stored as Box<T>, so callback must wrap the result.
    selfReference: () =>
      `|dec| Box::new(${ctx.currentTypeName}::decode_from(dec))`,
    object: (t) => `|dec| ${t.name}::decode_from(dec)`,
    union: (t) => `|dec| ${t.name}::decode_from(dec)`,
  });
}

// Shared body for encode-diff — renders the expression using the provided
// names for the encoder and the two values. Direct and callback wrappers
// below supply the names and the appropriate wrapping.
//
// In "element" context (inside array/optional/record update callbacks and
// push_field_diff callbacks), boolean emits a no-op — the caller already
// signalled "this element changed" via membership in the update list, and the
// decoder flips on update. Matches TS/C# binary format.
function encodeDiffBody(
  ctx: GeneratorContext,
  type: Type,
  a: string,
  b: string,
  enc: string,
  context: DiffContext = "value",
): string {
  return dispatch(type, {
    string: () => `${enc}.push_string_diff(${a}, ${b})`,
    int: (t) => {
      const s = intStrategy(t);
      if (s.kind === "packed") {
        return `${enc}.push_enum_diff(${intBitOffsetRs(a, s.offset)}, ${intBitOffsetRs(b, s.offset)}, ${s.numBits})`;
      }
      if (s.kind === "unsigned") {
        return s.min === 0
          ? `${enc}.push_uint_diff(${a}, ${b})`
          : `${enc}.push_uint_diff(${a} - ${s.min}, ${b} - ${s.min})`;
      }
      return `${enc}.push_int_diff(${a}, ${b})`;
    },
    float: (t) => {
      const s = floatStrategy(t);
      return s.kind === "quantized"
        ? `${enc}.push_float_quantized_diff(${a}, ${b}, ${s.precision}_f32)`
        : `${enc}.push_float_diff(${a}, ${b})`;
    },
    boolean: () =>
      context === "element" ? "{}" : `${enc}.push_boolean_diff(${a}, ${b})`,
    enum: (t) =>
      `${enc}.push_enum_diff(${a}.to_u32(), ${b}.to_u32(), ${t.numBits})`,
    array: (t) => {
      const innerEncode = renderEncodeCallback(ctx, t.value);
      const innerEquals = renderEqualsCallback(ctx, t.value);
      const innerDiff = renderEncodeDiffCallback(ctx, t.value);
      return `${enc}.push_array_diff(${a}, ${b}, ${innerEquals}, ${innerEncode}, ${innerDiff})`;
    },
    optional: (t) => {
      const innerEncode = renderEncodeCallback(ctx, t.value);
      const innerDiff = renderEncodeDiffCallback(ctx, t.value);
      return `${enc}.push_optional_diff(${a}, ${b}, ${innerEncode}, ${innerDiff})`;
    },
    record: (t) => {
      const keyEncode = renderEncodeCallback(ctx, t.key);
      const valEncode = renderEncodeCallback(ctx, t.value);
      const valEquals = renderEqualsCallback(ctx, t.value);
      const valDiff = renderEncodeDiffCallback(ctx, t.value);
      return `${enc}.push_record_diff(${a}, ${b}, ${valEquals}, ${keyEncode}, ${valEncode}, ${valDiff})`;
    },
    // Objects/unions/self-refs use field-only encode_diff_into
    // (unions include the same_type bit internally).
    object: (t) => `${t.name}::encode_diff_into(${a}, ${b}, ${enc})`,
    selfReference: () =>
      `${ctx.currentTypeName}::encode_diff_into(${a}, ${b}, ${enc})`,
    union: (t) => `${t.name}::encode_diff_into(${a}, ${b}, ${enc})`,
  });
}

// Closure form for use in push_array_diff / push_optional_diff / push_record_diff
// / push_field_diff. The callback is invoked only for elements already known to
// differ, so we pass "element" context — boolean lets the decoder flip.
// Takes `(encoder, old, new)` — ref-types receive borrowed refs; Copy types
// destructure via `&a, &b` to get values.
function renderEncodeDiffCallback(ctx: GeneratorContext, type: Type): string {
  const binder = callbackDiffBinder(type, false);
  return `|enc, ${binder}| ${encodeDiffBody(ctx, type, "a", "b", "enc", "element")}`;
}

// Shared body for decode-diff — renders the expression using the provided
// names for the decoder and the old value. Direct and callback wrappers
// below supply the names and the appropriate wrapping.
//
// In "element" context, boolean flips the old value — caller implies changed,
// no bytes were written on the encode side. Matches TS/C# binary format.
function decodeDiffBody(
  ctx: GeneratorContext,
  type: Type,
  a: string,
  dec: string,
  context: DiffContext = "value",
): string {
  return dispatch(type, {
    string: () => `${dec}.next_string_diff(${a})`,
    int: (t) => {
      const s = intStrategy(t);
      if (s.kind === "packed") {
        const signed = s.offset < 0;
        return intBitDecodeRs(
          `${dec}.next_enum_diff(${intBitOffsetRs(a, s.offset)}, ${s.numBits})`,
          s.offset,
          signed,
        );
      }
      if (s.kind === "unsigned") {
        return s.min === 0
          ? `${dec}.next_uint_diff(${a})`
          : `${dec}.next_uint_diff(${a} - ${s.min}) + ${s.min}`;
      }
      return `${dec}.next_int_diff(${a})`;
    },
    float: (t) => {
      const s = floatStrategy(t);
      return s.kind === "quantized"
        ? `${dec}.next_float_quantized_diff(${a}, ${s.precision}_f32)`
        : `${dec}.next_float_diff(${a})`;
    },
    boolean: () =>
      context === "element" ? `!${a}` : `${dec}.next_boolean_diff(${a})`,
    enum: (t) =>
      `${t.name}::from_u32(${dec}.next_enum_diff(${a}.to_u32(), ${t.numBits}))`,
    array: (t) => {
      const innerDecode = renderDecodeCallback(ctx, t.value);
      const innerDiff = renderDecodeDiffCallback(ctx, t.value);
      return `${dec}.next_array_diff(${a}, ${innerDecode}, ${innerDiff})`;
    },
    optional: (t) => {
      const innerDecode = renderDecodeCallback(ctx, t.value);
      const innerDiff = renderDecodeDiffCallback(ctx, t.value);
      return `${dec}.next_optional_diff(${a}, ${innerDecode}, ${innerDiff})`;
    },
    record: (t) => {
      const keyDecode = renderDecodeCallback(ctx, t.key);
      const valDecode = renderDecodeCallback(ctx, t.value);
      const valDiff = renderDecodeDiffCallback(ctx, t.value);
      return `${dec}.next_record_diff(${a}, ${keyDecode}, ${valDecode}, ${valDiff})`;
    },
    // Objects/unions/self-refs use field-only decode_diff_from
    // (unions include the same_type bit internally). Self-refs are Box<T>,
    // so the constructor wraps the result.
    object: (t) => `${t.name}::decode_diff_from(${a}, ${dec})`,
    selfReference: () =>
      `Box::new(${ctx.currentTypeName}::decode_diff_from(${a}, ${dec}))`,
    union: (t) => `${t.name}::decode_diff_from(${a}, ${dec})`,
  });
}

// Closure form for use in next_array_diff / next_optional_diff / next_record_diff
// / next_field_diff. Passes "element" context — boolean flips the old value
// since caller implies changed.
// Takes `(decoder, old)` — ref-types receive a borrowed ref; Copy types
// destructure via `&a` to get a value.
function renderDecodeDiffCallback(ctx: GeneratorContext, type: Type): string {
  const binder = callbackDiffBinder(type, true);
  return `|dec, ${binder}| ${decodeDiffBody(ctx, type, "a", "dec", "element")}`;
}

// Generate an equals closure for use with push_array_diff and push_field_diff
function renderEqualsCallback(ctx: GeneratorContext, type: Type): string {
  return dispatch(type, {
    string: () => `|x, y| x == y`,
    int: () => `|x, y| x == y`,
    boolean: () => `|x, y| x == y`,
    enum: () => `|x, y| x == y`,
    float: (t) => {
      const s = floatStrategy(t);
      return s.kind === "quantized"
        ? `|&x, &y| delta_pack::equals_float_quantized(x, y, ${s.precision}_f32)`
        : `|&x, &y| delta_pack::equals_float(x, y)`;
    },
    array: (t) =>
      isPrimitiveOrEnum(t.value)
        ? `|x, y| x == y`
        : `|x, y| delta_pack::equals_array(x, y, ${renderEqualsCallback(ctx, t.value)})`,
    optional: (t) =>
      isPrimitiveOrEnum(t.value)
        ? `|x, y| x == y`
        : `|x, y| delta_pack::equals_optional(x, y, ${renderEqualsCallback(ctx, t.value)})`,
    record: (t) =>
      isPrimitiveOrEnum(t.value)
        ? `|x, y| x == y`
        : `|x, y| delta_pack::equals_record(x, y, ${renderEqualsCallback(ctx, t.value)})`,
    selfReference: () => `|x, y| x.equals(y)`,
    object: () => `|x, y| x.equals(y)`,
    union: () => `|x, y| x.equals(y)`,
  });
}

function renderDecode(ctx: GeneratorContext, type: Type): string {
  return dispatch(type, {
    string: () => `decoder.next_string()`,
    int: (t) => {
      const s = intStrategy(t);
      if (s.kind === "packed") {
        const signed = s.offset < 0;
        return intBitDecodeRs(
          `decoder.next_enum(${s.numBits})`,
          s.offset,
          signed,
        );
      }
      if (s.kind === "unsigned") {
        return s.min === 0
          ? `decoder.next_uint()`
          : `decoder.next_uint() + ${s.min}`;
      }
      return `decoder.next_int()`;
    },
    float: (t) => {
      const s = floatStrategy(t);
      return s.kind === "quantized"
        ? `decoder.next_float_quantized(${s.precision}_f32)`
        : `decoder.next_float()`;
    },
    boolean: () => `decoder.next_boolean()`,
    enum: (t) => `${t.name}::from_u32(decoder.next_enum(${t.numBits}))`,
    array: (t) => {
      const innerDecode = renderDecodeCallback(ctx, t.value);
      return `decoder.next_array(${innerDecode})`;
    },
    optional: (t) => {
      const innerDecode = renderDecodeCallback(ctx, t.value);
      return `decoder.next_optional(${innerDecode})`;
    },
    record: (t) => {
      const keyDecode = renderDecodeCallback(ctx, t.key);
      const valDecode = renderDecodeCallback(ctx, t.value);
      return `decoder.next_record(${keyDecode}, ${valDecode})`;
    },
    selfReference: () =>
      `Box::new(${ctx.currentTypeName}::decode_from(decoder))`,
    object: (t) => `${t.name}::decode_from(decoder)`,
    union: (t) => `${t.name}::decode_from(decoder)`,
  });
}

// Direct form — `a` and `b` are expressions (field accesses, typically).
// Copy types pass by value; ref types get prefixed with `&`.
function renderEncodeDiff(
  ctx: GeneratorContext,
  type: Type,
  a: string,
  b: string,
): string {
  return encodeDiffBody(
    ctx,
    type,
    directDiffArg(a, type),
    directDiffArg(b, type),
    "encoder",
  );
}

// Direct form — `key` is an expression for the old value (field access).
// Copy types use the value; ref types get prefixed with `&`.
function renderDecodeDiff(
  ctx: GeneratorContext,
  type: Type,
  key: string,
): string {
  return decodeDiffBody(ctx, type, directDiffArg(key, type), "decoder");
}
