import { Type, NamedType, IntType, FloatType } from "@hpx7/delta-pack";
import type { CodegenOptions } from "./index.js";
import { dispatch } from "./visitor.js";

export function codegenRust(
  schema: Record<string, Type>,
  _options?: CodegenOptions,
): string {
  const parts: string[] = [];
  for (const [name, type] of Object.entries(schema)) {
    if (type.type === "enum") {
      parts.push(renderEnum(name, type.options));
    } else if (type.type === "object") {
      parts.push(renderObject(name, type.properties));
    } else if (type.type === "union") {
      parts.push(renderUnion(name, type.options));
    }
  }

  return `// Auto-generated by DeltaPack - do not edit
#![allow(dead_code, unused_imports, clippy::all)]

use delta_pack::{DeltaPack, IndexMap};
use serde::{Deserialize, Serialize};

${parts.join("\n\n")}
`;
}

// ============ Name helpers ============

const RUST_KEYWORDS = new Set([
  "as",
  "break",
  "const",
  "continue",
  "crate",
  "else",
  "enum",
  "extern",
  "false",
  "fn",
  "for",
  "if",
  "impl",
  "in",
  "let",
  "loop",
  "match",
  "mod",
  "move",
  "mut",
  "pub",
  "ref",
  "return",
  "self",
  "Self",
  "static",
  "struct",
  "super",
  "trait",
  "true",
  "type",
  "unsafe",
  "use",
  "where",
  "while",
  "async",
  "await",
  "dyn",
  "bool",
  "str",
  "f32",
  "f64",
]);

function toSnakeCase(str: string): string {
  return str
    .replace(/([A-Z])/g, "_$1")
    .toLowerCase()
    .replace(/^_/, "");
}

// Returns [rustFieldName, needsSerdeRename].
// Serde rename is emitted whenever the Rust field name diverges from the
// original (camelCase original, keyword collision).
function toRustFieldName(str: string): [string, boolean] {
  const snake = toSnakeCase(str);
  if (RUST_KEYWORDS.has(snake)) {
    return [`${snake}_`, true];
  }
  return [snake, snake !== str];
}

function toPascalCase(str: string): string {
  return str ? str.charAt(0).toUpperCase() + str.slice(1) : str;
}

// ============ Enum Renderer ============

function renderEnum(name: string, options: readonly string[]): string {
  const variants = options
    .map((opt) => {
      const pascal = toPascalCase(opt);
      const attrs: string[] = [];
      if (pascal !== opt) {
        // Serde carries the original wire name for JSON interop.
        attrs.push(`    #[serde(rename = "${opt}")]`);
      }
      attrs.push(`    ${pascal},`);
      return attrs.join("\n");
    })
    .join("\n");

  return `#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize, DeltaPack)]
pub enum ${name} {
${variants}
}`;
}

// ============ Union Renderer ============

function renderUnion(name: string, options: readonly NamedType[]): string {
  const variants = options
    .map((opt) => `    ${opt.name}(${opt.name}),`)
    .join("\n");

  return `#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, DeltaPack)]
pub enum ${name} {
${variants}
}`;
}

// ============ Object Renderer ============

function renderObject(name: string, properties: Record<string, Type>): string {
  const fieldLines = Object.entries(properties)
    .map(([origName, type]) => {
      const [rustName, needsSerdeRename] = toRustFieldName(origName);
      const attrs: string[] = [];
      if (needsSerdeRename) {
        attrs.push(`    #[serde(rename = "${origName}")]`);
      }
      const deltaAttr = renderDeltaPackAttr(type);
      if (deltaAttr !== null) {
        attrs.push(`    ${deltaAttr}`);
      }
      attrs.push(`    pub ${rustName}: ${renderType(name, type)},`);
      return attrs.join("\n");
    })
    .join("\n");

  return `#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, DeltaPack)]
pub struct ${name} {
${fieldLines}
}`;
}

// ============ Attribute emission ============

// Only emits `#[delta_pack(...)]` when the derive's defaults wouldn't
// reconstruct the same schema. Specifically:
//   - plain `i64` / `u64` fields (bounded or not) need an attr only when the
//     YAML has bounds that diverge from the implicit "u64 ⇒ min=0" default.
//   - `f32` needs an attr only when YAML specifies precision.
function renderDeltaPackAttr(type: Type): string | null {
  if (type.type === "int") return renderIntAttr(type);
  if (type.type === "float") return renderFloatAttr(type);
  return null;
}

function renderIntAttr(t: IntType): string | null {
  const parts: string[] = [];
  if (t.min !== undefined) parts.push(`min = ${t.min}`);
  if (t.max !== undefined) parts.push(`max = ${t.max}`);
  if (parts.length === 0) return null;
  // u64 fields get min=0 implicitly from the derive. If that's the only bound,
  // no attr is needed.
  if (t.min === 0 && t.max === undefined) return null;
  return `#[delta_pack(range(${parts.join(", ")}))]`;
}

function renderFloatAttr(t: FloatType): string | null {
  if (t.precision !== undefined && t.precision !== 0) {
    return `#[delta_pack(precision = ${t.precision})]`;
  }
  return null;
}

// ============ Type rendering ============

function renderType(currentTypeName: string, type: Type): string {
  return dispatch(type, {
    string: () => "String",
    int: (t) => (t.min != null && t.min >= 0 ? "u64" : "i64"),
    float: () => "f32",
    boolean: () => "bool",
    enum: (t) => t.name,
    array: (t) => `Vec<${renderType(currentTypeName, t.value)}>`,
    optional: (t) => `Option<${renderType(currentTypeName, t.value)}>`,
    record: (t) =>
      `IndexMap<${renderType(currentTypeName, t.key)}, ${renderType(currentTypeName, t.value)}>`,
    selfReference: () => `Box<${currentTypeName}>`,
    object: (t) => t.name,
    union: (t) => t.name,
  });
}
