// Auto-generated by DeltaPack - do not edit
using DeltaPack;

namespace Generated
{
    public enum Color
    {
        RED = 0,
        BLUE = 1,
        GREEN = 2,
        YELLOW = 3
    }

    [DeltaPack]
    public partial class Player
    {
        public string Id { get; set; } = "";
        public string Name { get; set; } = "";
        public long Score { get; set; }
        public bool IsActive { get; set; }
        public Player? Partner { get; set; }
    }

    [DeltaPack]
    public partial class Position
    {
        [DeltaPackPrecision(0.1f)] public float X { get; set; }
        [DeltaPackPrecision(0.1f)] public float Y { get; set; }
    }

    [DeltaPack]
    public partial class Velocity
    {
        public float Vx { get; set; }
        public float Vy { get; set; }
    }

    [DeltaPack]
    public partial class Entity
    {
        public string Id { get; set; } = "";
        public Position Position { get; set; } = Position.Default();
    }

    [DeltaPack]
    public partial class MoveAction : GameAction
    {
        public long X { get; set; }
        public long Y { get; set; }
    }

    [DeltaPack]
    public partial class AttackAction : GameAction
    {
        public string TargetId { get; set; } = "";
        [DeltaPackRange(0)] public long Damage { get; set; }
    }

    [DeltaPack]
    public partial class UseItemAction : GameAction
    {
        public string ItemId { get; set; } = "";
    }

    [DeltaPack]
    [DeltaPackUnion(typeof(MoveAction), typeof(AttackAction), typeof(UseItemAction))]
    public abstract partial class GameAction { }

    [DeltaPack]
    public partial class GameState
    {
        public DeltaPack.DPList<Player> Players { get; set; } = new DeltaPack.DPList<Player>();
        public string? CurrentPlayer { get; set; }
        [DeltaPackRange(0)] public long Round { get; set; }
        public DeltaPack.DPDict<string, string> Metadata { get; set; } = new DeltaPack.DPDict<string, string>();
        public Color? WinningColor { get; set; }
        public GameAction? LastAction { get; set; }
    }

    [DeltaPack]
    public partial class Inventory
    {
        public DeltaPack.DPList<DeltaPack.DPDict<string, long>>? Items { get; set; }
    }

    [DeltaPack]
    public partial class PlayerRegistry
    {
        public DeltaPack.DPDict<string, Player> Players { get; set; } = new DeltaPack.DPDict<string, Player>();
    }
}
