UserId: string

HairColor:
  - BLACK
  - BROWN
  - BLOND
  - RED
  - WHITE
  - OTHER

Address:
  street: string
  zip: string
  state: string

User:
  id: UserId
  name: string
  age: uint
  weight: float
  married: boolean
  hairColor: HairColor
  address: Address?
  children: UserId[]
  metadata: string,string
