using System.Collections.Generic;
using System.Linq;
using DeltaPack.SourceGenerator.Model;

namespace DeltaPack.SourceGenerator.Emit;

internal static class ObjectEmitter
{
    public static string Emit(TypeDef def, ModelRegistry reg, bool hidesBase = false)
    {
        var w = new CodeWriter();
        w.Line("// <auto-generated/> DeltaPack.SourceGenerator");
        w.Line("#nullable enable");
        w.Line("using System.Linq;");
        w.Line("using DeltaPack;");
        w.Line();

        int openScopes = Scaffold.OpenNamespaceAndContainingTypes(w, def);
        using (w.Block(BuildClassHeader(def)))
        {
            EmitStaticMembers(w, def, reg, hidesBase);
        }
        Scaffold.CloseScopes(w, openScopes);

        return w.ToString();
    }

    private static string BuildClassHeader(TypeDef def)
    {
        // Preserve `abstract` modifier on the partial; the user already declared the type.
        var abstractKw = def.IsAbstract ? "abstract " : "";
        var kindKw = def.IsStruct ? "struct" : "class";
        // Tracked classes need to declare the interface on at least one partial part.
        var bases = def.IsTracked ? " : DeltaPack.ITrackedObject" : "";
        return $"{abstractKw}partial {kindKw} {def.SimpleName}{bases}";
    }

    private static void EmitStaticMembers(CodeWriter w, TypeDef def, ModelRegistry reg, bool hidesBase)
    {
        // Only methods with an IDENTICAL signature to a base-class method need the `new`
        // modifier. For variants of a union, that's Default(), FromJson(JsonElement),
        // Decode(byte[]), Decode_(Decoder) — everything else has a variant-specific parameter
        // type that makes the signature distinct.
        var newIfHides = hidesBase ? "new " : "";

        EmitDefault(w, def, newIfHides);
        w.Line();
        EmitFromJson(w, def, reg, newIfHides);
        w.Line();
        EmitToJson(w, def, reg, "");
        w.Line();
        EmitClone(w, def, reg, "");
        w.Line();
        EmitEquals(w, def, reg, "");
        w.Line();
        EmitEncode(w, def, reg, "");
        w.Line();
        EmitEncodeDiff(w, def, reg, "");
        w.Line();
        EmitDecode(w, def, reg, newIfHides);
        w.Line();
        EmitDecodeDiff(w, def, reg, "");

        if (def.IsTracked)
        {
            w.Line();
            TrackingEmitter.EmitTrackingMembers(w, def, reg);
        }
        else
        {
            // Users may opt into `partial` property syntax without enabling tracking so they
            // can flip `[DeltaPackTracked]` on later without touching every property. Emit
            // trivial implementing declarations for each such property.
            foreach (var f in def.Fields)
            {
                if (!f.IsDeclaredPartial) continue;
                w.Line();
                EmitTrivialPartialProperty(w, f, reg);
            }
        }
    }

    private static void EmitTrivialPartialProperty(CodeWriter w, FieldModel f, ModelRegistry reg)
    {
        var declared = ExpressionRenderer.CSharpType(f.Type, reg);
        var backing = "__dp_" + char.ToLowerInvariant(f.Name[0]) + f.Name.Substring(1);
        var defaultInit = ExpressionRenderer.DefaultInitializer(f.Type, reg);
        w.Line($"private {declared} {backing} = {defaultInit};");
        w.Line($"public partial {declared} {f.Name} {{ get => {backing}; set => {backing} = value; }}");
    }

    private static void EmitFromJson(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}{def.SimpleName} FromJson(System.Text.Json.JsonElement json)"))
        {
            using (w.Block("return new()"))
            {
                foreach (var f in def.Fields)
                    w.Line($"{f.Name} = {ExpressionRenderer.FromJsonField(f, reg)},");
            }
            w.Line(";");
        }
    }

    private static void EmitToJson(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}System.Text.Json.Nodes.JsonObject ToJson({def.SimpleName} obj)"))
        {
            w.Line("var result = new System.Text.Json.Nodes.JsonObject();");
            foreach (var f in def.Fields)
                ExpressionRenderer.ToJsonField(w, f, reg, "obj", "result");
            w.Line("return result;");
        }
    }

    private static void EmitDefault(CodeWriter w, TypeDef def, string newKw)
    {
        w.Line($"public static {newKw}{def.SimpleName} Default() => new();");
    }

    private static void EmitClone(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        if (def.IsTracked)
        {
            // Split into public `Clone` (registers the snapshot) and internal `CloneChild_`
            // (does the work without registering). Nested clones reached via CreateSnapshot
            // factories and tracked-reference fields use `CloneChild_`, so only the root
            // ever ends up in the snapshot registry. Otherwise, cloning a tree of N tracked
            // instances meant N registry entries + N PruneDeleted walks — quadratic at scale.
            using (w.Block($"public static {newKw}{def.SimpleName} Clone({def.SimpleName} obj)"))
            {
                w.Line("var result = CloneChild_(obj);");
                w.Line("DeltaPack.DirtyTracking.RegisterSnapshot(result, obj);");
                w.Line("return result;");
            }
            w.Line();
            using (w.Block($"internal static {def.SimpleName} CloneChild_({def.SimpleName} obj)"))
            {
                EmitTrackedCloneBody(w, def, reg);
            }
        }
        else
        {
            using (w.Block($"public static {newKw}{def.SimpleName} Clone({def.SimpleName} obj)"))
            {
                using (w.Block("return new()"))
                {
                    foreach (var f in def.Fields)
                        w.Line($"{f.Name} = {ExpressionRenderer.CloneInline(f.Type, $"obj.{f.Name}", reg)},");
                }
                w.Line(";");
            }
        }
    }

    /// <summary>
    /// Emits the tracked-type Clone body as direct backing-field writes plus per-child Reparent
    /// calls. Does NOT call <c>RegisterSnapshot</c> — that's handled by the public <c>Clone</c>
    /// wrapper at the root only. Writing to backing fields directly also avoids the per-field
    /// NextVersion/dirty-map writes/PropagateToParent that the partial-property setters would
    /// run — wasted work on a freshly-built snapshot.
    /// </summary>
    private static void EmitTrackedCloneBody(CodeWriter w, TypeDef def, ModelRegistry reg)
    {
        w.Line($"var result = new {def.SimpleName}();");
        for (int slot = 0; slot < def.Fields.Length; slot++)
        {
            var f = def.Fields[slot];
            var backing = ExpressionRenderer.TrackingBackingField(f);
            // Pass inTrackedContext=true so CloneInline emits `CloneChild_` (not `Clone`)
            // for any nested tracked references — no redundant registry entries.
            var cloneExpr = ExpressionRenderer.CloneInline(f.Type, $"obj.{f.Name}", reg, inTrackedContext: true);
            w.Line($"result.{backing} = {cloneExpr};");

            if (ExpressionRenderer.ChildIsTrackable(f.Type, reg))
            {
                // Optional<T> may legitimately be null; other trackable fields won't be.
                // Use `is IDirtyTracked` to cover both cases uniformly and null-safely.
                w.Line($"if (result.{backing} is DeltaPack.IDirtyTracked __t_{f.Name})");
                w.Line($"    DeltaPack.DirtyTracking.ReparentToObject(__t_{f.Name}, result, {slot});");
            }
        }
        w.Line("return result;");
    }

    private static void EmitEquals(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}bool Equals({def.SimpleName} a, {def.SimpleName} b)"))
        {
            if (def.Fields.Length == 0)
            {
                w.Line("return true;");
                return;
            }
            var parts = def.Fields.Select(f =>
                ExpressionRenderer.EqualsInline(f.Type, $"a.{f.Name}", $"b.{f.Name}", reg)).ToList();
            w.Line("return " + string.Join(" &&\n    ", parts) + ";");
        }
    }

    private static void EmitEncode(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}byte[] Encode({def.SimpleName} obj)"))
        {
            w.Line("var encoder = new DeltaPack.Encoder();");
            w.Line("Encode_(obj, encoder);");
            w.Line("return encoder.ToBuffer();");
        }
        w.Line();
        using (w.Block($"internal static {newKw}void Encode_({def.SimpleName} obj, DeltaPack.Encoder encoder)"))
        {
            foreach (var f in def.Fields)
                ExpressionRenderer.EncodeField(w, f, reg, "obj");
        }
    }

    private static void EmitEncodeDiff(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}byte[] EncodeDiff({def.SimpleName} a, {def.SimpleName} b)"))
        {
            w.Line("var encoder = new DeltaPack.Encoder();");
            // Method group `EncodeDiff_` binds to `Action<T, T, Encoder>` — the runtime caches
            // the delegate per type, avoiding the per-call closure that a `() => ...` lambda
            // would allocate.
            w.Line("encoder.PushObjectDiff(a, b, Equals, EncodeDiff_);");
            w.Line("return encoder.ToBuffer();");
        }
        w.Line();
        using (w.Block($"internal static {newKw}void EncodeDiff_({def.SimpleName} a, {def.SimpleName} b, DeltaPack.Encoder encoder)"))
        {
            if (def.IsTracked)
            {
                // Hoist the baseline snapshot version once — each inlined field diff block
                // below compares against this. Without the hoist, every field would repeat
                // the same property read (virtual on IDirtyTracked); with N fields that's
                // O(N) redundant reads per tracked object in the hot path.
                w.Line("var __dp_minVersion = a.SnapshotVersion;");
            }
            for (int i = 0; i < def.Fields.Length; i++)
                ExpressionRenderer.EncodeDiffField(w, def.Fields[i], i, reg, "a", "b", def.IsTracked);
        }
    }

    private static void EmitDecode(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}{def.SimpleName} Decode(byte[] buf)"))
        {
            w.Line("var decoder = new DeltaPack.Decoder(buf);");
            w.Line("return Decode_(decoder);");
        }
        w.Line();
        using (w.Block($"internal static {newKw}{def.SimpleName} Decode_(DeltaPack.Decoder decoder)"))
        {
            using (w.Block("return new()"))
            {
                foreach (var f in def.Fields)
                    w.Line($"{f.Name} = {ExpressionRenderer.DecodeInline(f.Type, reg)},");
            }
            w.Line(";");
        }
    }

    private static void EmitDecodeDiff(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}{def.SimpleName} DecodeDiff({def.SimpleName} obj, byte[] diff)"))
        {
            w.Line("var decoder = new DeltaPack.Decoder(diff);");
            w.Line("return decoder.NextObjectDiff(obj, () => DecodeDiff_(obj, decoder));");
        }
        w.Line();
        using (w.Block($"internal static {newKw}{def.SimpleName} DecodeDiff_({def.SimpleName} obj, DeltaPack.Decoder decoder)"))
        {
            using (w.Block("return new()"))
            {
                foreach (var f in def.Fields)
                    w.Line($"{f.Name} = {ExpressionRenderer.DecodeDiffField(f, reg, "obj")},");
            }
            w.Line(";");
        }
    }
}

internal static class Scaffold
{
    public static int OpenNamespaceAndContainingTypes(CodeWriter w, TypeDef def)
    {
        int scopes = 0;
        if (!string.IsNullOrEmpty(def.Namespace))
        {
            w.Line($"namespace {def.Namespace}");
            w.Line("{");
            w.Indent();
            scopes++;
        }
        foreach (var container in def.ContainingTypes)
        {
            w.Line($"partial class {container}");
            w.Line("{");
            w.Indent();
            scopes++;
        }
        return scopes;
    }

    public static void CloseScopes(CodeWriter w, int scopes)
    {
        for (int i = 0; i < scopes; i++)
        {
            w.Dedent();
            w.Line("}");
        }
    }
}
