using System.Collections.Generic;
using System.Linq;
using DeltaPack.SourceGenerator.Model;

namespace DeltaPack.SourceGenerator.Emit;

internal static class ObjectEmitter
{
    public static string Emit(TypeDef def, ModelRegistry reg, bool hidesBase = false)
    {
        var w = new CodeWriter();
        w.Line("// <auto-generated/> DeltaPack.SourceGenerator");
        w.Line("#nullable enable");
        w.Line("using System.Linq;");
        w.Line("using DeltaPack;");
        w.Line();

        int openScopes = Scaffold.OpenNamespaceAndContainingTypes(w, def);
        using (w.Block(BuildClassHeader(def)))
        {
            EmitStaticMembers(w, def, reg, hidesBase);
        }
        Scaffold.CloseScopes(w, openScopes);

        return w.ToString();
    }

    private static string BuildClassHeader(TypeDef def)
    {
        // Preserve `abstract` modifier on the partial; the user already declared the type.
        var abstractKw = def.IsAbstract ? "abstract " : "";
        var kindKw = def.IsStruct ? "struct" : "class";
        // Classes with any partial property need to declare the tracking interface on at
        // least one partial part. Classes with no partial properties stay free of any
        // tracking-interface plumbing (Unity-friendly).
        var bases = def.IsTracked ? " : DeltaPack.ITrackedObject" : "";
        return $"{abstractKw}partial {kindKw} {def.SimpleName}{bases}";
    }

    private static void EmitStaticMembers(CodeWriter w, TypeDef def, ModelRegistry reg, bool hidesBase)
    {
        // Only methods with an IDENTICAL signature to a base-class method need the `new`
        // modifier. For variants of a union, that's Default(), FromJson(JsonElement),
        // Decode(byte[]), Decode_(Decoder) — everything else has a variant-specific parameter
        // type that makes the signature distinct.
        var newIfHides = hidesBase ? "new " : "";

        EmitDefault(w, def, newIfHides);
        w.Line();
        EmitFromJson(w, def, reg, newIfHides);
        w.Line();
        EmitToJson(w, def, reg, "");
        w.Line();
        EmitClone(w, def, reg, "");
        w.Line();
        EmitEquals(w, def, reg, "");
        w.Line();
        EmitEncode(w, def, reg, "");
        w.Line();
        EmitEncodeDiff(w, def, reg, "");
        w.Line();
        EmitDecode(w, def, reg, newIfHides);
        w.Line();
        EmitDecodeDiff(w, def, reg, "");
        // Structs can't satisfy `where T : class` on SyncSession<T>, skip them.
        if (!def.IsStruct)
        {
            w.Line();
            EmitCreateSyncSession(w, def, newIfHides);
        }

        if (def.IsTracked)
        {
            w.Line();
            TrackingEmitter.EmitTrackingMembers(w, def, reg);
        }
    }

    private static void EmitFromJson(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}{def.SimpleName} FromJson(System.Text.Json.JsonElement json)"))
        {
            using (w.Block("return new()"))
            {
                foreach (var f in def.Fields)
                    w.Line($"{f.Name} = {ExpressionRenderer.FromJsonField(f, reg)},");
            }
            w.Line(";");
        }
    }

    private static void EmitToJson(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}System.Text.Json.Nodes.JsonObject ToJson({def.SimpleName} obj)"))
        {
            w.Line("var result = new System.Text.Json.Nodes.JsonObject();");
            foreach (var f in def.Fields)
                ExpressionRenderer.ToJsonField(w, f, reg, "obj", "result");
            w.Line("return result;");
        }
    }

    private static void EmitDefault(CodeWriter w, TypeDef def, string newKw)
    {
        w.Line($"public static {newKw}{def.SimpleName} Default() => new();");
        if (def.IsTracked)
        {
            // Tracker-aware factory: child tracked instances are field-initialized with
            // Tracker.Default and adopt this instance's tracker lazily on first getter access
            // (via TrackingOps.ReparentToObject). The shared-clock invariant means that's safe
            // — dirty stamps are universally comparable across trackers.
            w.Line();
            w.Line($"public static {def.SimpleName} Default(DeltaPack.Tracker tracker)");
            using (w.Block(""))
            {
                w.Line($"var result = new {def.SimpleName}();");
                w.Line("((DeltaPack.IDirtyTracked)result).Tracker = tracker;");
                w.Line("return result;");
            }
        }
    }

    private static void EmitClone(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}{def.SimpleName} Clone({def.SimpleName} obj)"))
        {
            if (def.IsTracked)
            {
                // Write to backing fields directly rather than going through the partial-property
                // setters — setters would run NextVersion / dirty-map writes / PropagateToParent on
                // every field, which is wasted work on a freshly-built clone. The clone inherits
                // obj's tracker so it lands in the same domain. Non-partial fields go through the
                // user's auto-property setter (no tracking work to skip).
                w.Line($"var result = new {def.SimpleName}();");
                w.Line($"((DeltaPack.IDirtyTracked)result).Tracker = ((DeltaPack.IDirtyTracked)obj).Tracker;");
                for (int slot = 0; slot < def.Fields.Length; slot++)
                {
                    var f = def.Fields[slot];
                    var cloneExpr = ExpressionRenderer.CloneInline(f.Type, $"obj.{f.Name}", reg);
                    if (f.IsDeclaredPartial)
                    {
                        var backing = ExpressionRenderer.TrackingBackingField(f);
                        w.Line($"result.{backing} = {cloneExpr};");
                        if (ExpressionRenderer.ChildIsTrackable(f.Type, reg))
                        {
                            // Optional<T> may legitimately be null; other trackable fields won't be.
                            // Use `is IDirtyTracked` to cover both cases uniformly and null-safely.
                            w.Line($"if (result.{backing} is DeltaPack.IDirtyTracked __t_{f.Name})");
                            w.Line($"    DeltaPack.TrackingOps.ReparentToObject(__t_{f.Name}, result, {slot});");
                        }
                    }
                    else
                    {
                        w.Line($"result.{f.Name} = {cloneExpr};");
                    }
                }
                w.Line("return result;");
            }
            else
            {
                using (w.Block("return new()"))
                {
                    foreach (var f in def.Fields)
                        w.Line($"{f.Name} = {ExpressionRenderer.CloneInline(f.Type, $"obj.{f.Name}", reg)},");
                }
                w.Line(";");
            }
        }
    }

    private static void EmitEquals(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}bool Equals({def.SimpleName} a, {def.SimpleName} b)"))
        {
            if (def.Fields.Length == 0)
            {
                w.Line("return true;");
                return;
            }
            var parts = def.Fields.Select(f =>
                ExpressionRenderer.EqualsInline(f.Type, $"a.{f.Name}", $"b.{f.Name}", reg)).ToList();
            w.Line("return " + string.Join(" &&\n    ", parts) + ";");
        }
    }

    private static void EmitEncode(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}byte[] Encode({def.SimpleName} obj)"))
        {
            w.Line("var encoder = new DeltaPack.Encoder();");
            w.Line("Encode_(obj, encoder);");
            w.Line("return encoder.ToBuffer();");
        }
        w.Line();
        using (w.Block($"internal static {newKw}void Encode_({def.SimpleName} obj, DeltaPack.Encoder encoder)"))
        {
            foreach (var f in def.Fields)
                ExpressionRenderer.EncodeField(w, f, reg, "obj");
        }
    }

    private static void EmitEncodeDiff(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}byte[] EncodeDiff({def.SimpleName} a, {def.SimpleName} b)"))
        {
            w.Line("var encoder = new DeltaPack.Encoder();");
            if (def.IsStruct)
            {
                // Structs can't implement IDirtyTracked — pattern-match would be a compile error.
                w.Line("encoder.MinVersion = -1;");
            }
            else
            {
                // Class case: the `is` check resolves to true only when `a` actually implements
                // IDirtyTracked (i.e. the type has at least one partial property). For classes
                // with no partial properties the cast fails at runtime and we fall back to -1,
                // disabling the tracking filter. One emitted line covers both shapes.
                w.Line("encoder.MinVersion = a is DeltaPack.IDirtyTracked __dp_a ? __dp_a.Tracker.GetBaselineFor(a) : -1;");
            }
            w.Line("encoder.PushObjectDiff(a, b, Equals, EncodeDiff_);");
            w.Line("return encoder.ToBuffer();");
        }
        w.Line();
        using (w.Block($"internal static {newKw}void EncodeDiff_({def.SimpleName} a, {def.SimpleName} b, DeltaPack.Encoder encoder)"))
        {
            if (def.IsTracked)
            {
                // Hoist the baseline once — each inlined per-partial-field diff block compares
                // against this. Reading Encoder.MinVersion repeatedly inside the hot loop would
                // force a property-get at every field check.
                w.Line("var __dp_minVersion = encoder.MinVersion;");
            }
            for (int i = 0; i < def.Fields.Length; i++)
                ExpressionRenderer.EncodeDiffField(w, def.Fields[i], i, reg, "a", "b", def.Fields[i].IsDeclaredPartial);
        }
    }

    private static void EmitDecode(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}{def.SimpleName} Decode(byte[] buf)"))
        {
            w.Line("return Decode(buf, DeltaPack.Tracker.Default);");
        }
        w.Line();
        using (w.Block($"public static {newKw}{def.SimpleName} Decode(byte[] buf, DeltaPack.Tracker tracker)"))
        {
            w.Line("var decoder = new DeltaPack.Decoder(buf) { Tracker = tracker };");
            w.Line("return Decode_(decoder);");
        }
        w.Line();
        using (w.Block($"internal static {newKw}{def.SimpleName} Decode_(DeltaPack.Decoder decoder)"))
        {
            if (def.IsTracked)
            {
                // Bypass partial-property setters (avoids the aliasing guard + wasted dirty
                // bookkeeping) and stamp the result with the decoder's tracker so children
                // land in the right domain when reparented below. Non-partial fields go
                // through the user's auto-property setter.
                w.Line($"var result = new {def.SimpleName}();");
                w.Line("((DeltaPack.IDirtyTracked)result).Tracker = decoder.Tracker;");
                for (int slot = 0; slot < def.Fields.Length; slot++)
                {
                    var f = def.Fields[slot];
                    var decodeExpr = ExpressionRenderer.DecodeInline(f.Type, reg);
                    if (f.IsDeclaredPartial)
                    {
                        var backing = ExpressionRenderer.TrackingBackingField(f);
                        w.Line($"result.{backing} = {decodeExpr};");
                        if (ExpressionRenderer.ChildIsTrackable(f.Type, reg))
                        {
                            w.Line($"if (result.{backing} is DeltaPack.IDirtyTracked __t_{f.Name})");
                            w.Line($"    DeltaPack.TrackingOps.ReparentToObject(__t_{f.Name}, result, {slot});");
                        }
                    }
                    else
                    {
                        w.Line($"result.{f.Name} = {decodeExpr};");
                    }
                }
                w.Line("return result;");
            }
            else
            {
                using (w.Block("return new()"))
                {
                    foreach (var f in def.Fields)
                        w.Line($"{f.Name} = {ExpressionRenderer.DecodeInline(f.Type, reg)},");
                }
                w.Line(";");
            }
        }
    }

    private static void EmitCreateSyncSession(CodeWriter w, TypeDef def, string newKw)
    {
        // Union variants hide the base class's CreateSyncSession() — same name + empty params,
        // only the generic return type differs — so they need the `new` modifier.
        w.Line($"public static {newKw}DeltaPack.SyncSession<{def.SimpleName}> CreateSyncSession()");
        w.Line($"    => CreateSyncSession(DeltaPack.Tracker.Default);");
        w.Line();
        w.Line($"public static {newKw}DeltaPack.SyncSession<{def.SimpleName}> CreateSyncSession(DeltaPack.Tracker tracker)");
        w.Line($"    => new(tracker, Encode, buf => Decode(buf, tracker), EncodeDiff, DecodeDiff, Clone);");
    }

    private static void EmitDecodeDiff(CodeWriter w, TypeDef def, ModelRegistry reg, string newKw)
    {
        using (w.Block($"public static {newKw}{def.SimpleName} DecodeDiff({def.SimpleName} obj, byte[] diff)"))
        {
            w.Line("var decoder = new DeltaPack.Decoder(diff);");
            if (def.IsTracked)
            {
                // Inherit the snapshot's tracker so the decoded result lands in the same domain.
                w.Line("decoder.Tracker = ((DeltaPack.IDirtyTracked)obj).Tracker;");
            }
            w.Line("return decoder.NextObjectDiff(obj, () => DecodeDiff_(obj, decoder));");
        }
        w.Line();
        using (w.Block($"internal static {newKw}{def.SimpleName} DecodeDiff_({def.SimpleName} obj, DeltaPack.Decoder decoder)"))
        {
            if (def.IsTracked)
            {
                // Assign to backing fields directly rather than through the partial-property
                // setters — the setter-side aliasing guard would trip on unchanged fields
                // (NextFieldDiff returns the old snapshot's child, whose Parent points at
                // the snapshot, not the new result). Parent pointers are re-established
                // explicitly below, mirroring Clone. Non-partial fields go through the
                // user's auto-property setter.
                w.Line($"var result = new {def.SimpleName}();");
                w.Line("((DeltaPack.IDirtyTracked)result).Tracker = decoder.Tracker;");
                for (int slot = 0; slot < def.Fields.Length; slot++)
                {
                    var f = def.Fields[slot];
                    var decodeDiffExpr = ExpressionRenderer.DecodeDiffField(f, reg, "obj");
                    if (f.IsDeclaredPartial)
                    {
                        var backing = ExpressionRenderer.TrackingBackingField(f);
                        w.Line($"result.{backing} = {decodeDiffExpr};");
                        if (ExpressionRenderer.ChildIsTrackable(f.Type, reg))
                        {
                            w.Line($"if (result.{backing} is DeltaPack.IDirtyTracked __t_{f.Name})");
                            w.Line($"    DeltaPack.TrackingOps.ReparentToObject(__t_{f.Name}, result, {slot});");
                        }
                    }
                    else
                    {
                        w.Line($"result.{f.Name} = {decodeDiffExpr};");
                    }
                }
                w.Line("return result;");
            }
            else
            {
                using (w.Block("return new()"))
                {
                    foreach (var f in def.Fields)
                        w.Line($"{f.Name} = {ExpressionRenderer.DecodeDiffField(f, reg, "obj")},");
                }
                w.Line(";");
            }
        }
    }
}

internal static class Scaffold
{
    public static int OpenNamespaceAndContainingTypes(CodeWriter w, TypeDef def)
    {
        int scopes = 0;
        if (!string.IsNullOrEmpty(def.Namespace))
        {
            w.Line($"namespace {def.Namespace}");
            w.Line("{");
            w.Indent();
            scopes++;
        }
        foreach (var container in def.ContainingTypes)
        {
            w.Line($"partial class {container}");
            w.Line("{");
            w.Indent();
            scopes++;
        }
        return scopes;
    }

    public static void CloseScopes(CodeWriter w, int scopes)
    {
        for (int i = 0; i < scopes; i++)
        {
            w.Dedent();
            w.Line("}");
        }
    }
}
