using System.Collections.Generic;
using System.Linq;
using DeltaPack.SourceGenerator.Model;

namespace DeltaPack.SourceGenerator.Emit;

/// <summary>
/// Emits the union base-class dispatcher. Mirrors the shape produced by
/// <c>cli/src/codegen/csharp.ts::renderUnion</c> except for FromJson/ToJson
/// (deferred to Phase 2).
/// </summary>
internal static class UnionEmitter
{
    public static string Emit(TypeDef def, ModelRegistry reg)
    {
        var w = new CodeWriter();
        w.Line("// <auto-generated/> DeltaPack.SourceGenerator");
        w.Line("#nullable enable");
        w.Line("using System.Linq;");
        w.Line("using DeltaPack;");
        w.Line();

        int scopes = Scaffold.OpenNamespaceAndContainingTypes(w, def);

        // Preserve the class's abstract modifier on the partial.
        using (w.Block($"abstract partial class {def.SimpleName}"))
        {
            EmitDispatch(w, def, reg);
        }

        Scaffold.CloseScopes(w, scopes);
        return w.ToString();
    }

    private static void EmitDispatch(CodeWriter w, TypeDef def, ModelRegistry reg)
    {
        var variants = def.UnionVariants.AsImmutableArray();
        if (variants.Length == 0) return;

        var numBits = ExpressionRenderer.EnumNumBits(variants.Length);
        var firstShort = Short(variants[0]);

        // Default → first variant's Default()
        w.Line($"public static {def.SimpleName} Default() => {variants[0]}.Default();");
        w.Line();

        // FromJson — supports both `{ "VariantName": {...} }` and `{ type: "VariantName", val: {...} }` shapes.
        var variantShortsCsv = string.Join(", ", variants.Select(v => "\"" + Short(v) + "\""));
        using (w.Block($"public static {def.SimpleName} FromJson(System.Text.Json.JsonElement json)"))
        {
            using (w.Block("if (json.TryGetProperty(\"type\", out var typeEl) && json.TryGetProperty(\"val\", out var val))"))
            {
                w.Line($"var typeName = DeltaPack.JsonHelpers.FindVariant(typeEl.GetString()!, {variantShortsCsv});");
                for (int i = 0; i < variants.Length; i++)
                {
                    var v = variants[i];
                    var prefix = i == 0 ? "if" : "else if";
                    w.Line($"{prefix} (typeName == \"{Short(v)}\") return {v}.FromJson(val);");
                }
                w.Line($"throw new System.InvalidOperationException($\"Unknown {def.SimpleName} type: {{typeEl.GetString()}}\");");
            }
            w.Line("var prop = json.EnumerateObject().FirstOrDefault();");
            using (w.Block("if (prop.Value.ValueKind != System.Text.Json.JsonValueKind.Undefined)"))
            {
                w.Line($"var typeName = DeltaPack.JsonHelpers.FindVariant(prop.Name, {variantShortsCsv});");
                w.Line("var valProp = prop.Value;");
                for (int i = 0; i < variants.Length; i++)
                {
                    var v = variants[i];
                    var prefix = i == 0 ? "if" : "else if";
                    w.Line($"{prefix} (typeName == \"{Short(v)}\") return {v}.FromJson(valProp);");
                }
            }
            w.Line($"throw new System.InvalidOperationException(\"Invalid {def.SimpleName} format\");");
        }
        w.Line();

        // ToJson — wraps variant's JSON in a single-key object: { "VariantName": {...} }
        using (w.Block($"public static System.Text.Json.Nodes.JsonObject ToJson({def.SimpleName} obj)"))
        {
            for (int i = 0; i < variants.Length; i++)
            {
                var v = variants[i];
                var local = LocalName(Short(v));
                var prefix = i == 0 ? "if" : "else if";
                w.Line($"{prefix} (obj is {v} {local}) return new System.Text.Json.Nodes.JsonObject {{ [\"{Short(v)}\"] = {v}.ToJson({local}) }};");
            }
            w.Line($"throw new System.InvalidOperationException($\"Unknown {def.SimpleName} type\");");
        }
        w.Line();

        // Clone
        using (w.Block($"public static {def.SimpleName} Clone({def.SimpleName} obj)"))
        {
            for (int i = 0; i < variants.Length; i++)
            {
                var v = variants[i];
                var shortName = Short(v);
                var local = LocalName(shortName);
                var prefix = i == 0 ? "if" : "else if";
                w.Line($"{prefix} (obj is {v} {local}) return {v}.Clone({local});");
            }
            w.Line($"throw new System.InvalidOperationException($\"Unknown {def.SimpleName} type\");");
        }
        w.Line();

        // Equals
        using (w.Block($"public static bool Equals({def.SimpleName} a, {def.SimpleName} b)"))
        {
            w.Line("if (a.GetType() != b.GetType()) return false;");
            for (int i = 0; i < variants.Length; i++)
            {
                var v = variants[i];
                var shortName = Short(v);
                var la = LocalName(shortName) + "A";
                var lb = LocalName(shortName) + "B";
                var prefix = i == 0 ? "if" : "else if";
                w.Line($"{prefix} (a is {v} {la} && b is {v} {lb}) return {v}.Equals({la}, {lb});");
            }
            w.Line("return false;");
        }
        w.Line();

        // Encode
        using (w.Block($"public static byte[] Encode({def.SimpleName} obj)"))
        {
            w.Line("var encoder = new DeltaPack.Encoder();");
            w.Line("Encode_(obj, encoder);");
            w.Line("return encoder.ToBuffer();");
        }
        w.Line();
        using (w.Block($"internal static void Encode_({def.SimpleName} obj, DeltaPack.Encoder encoder)"))
        {
            for (int i = 0; i < variants.Length; i++)
            {
                var v = variants[i];
                var local = LocalName(Short(v));
                var prefix = i == 0 ? "if" : "else if";
                using (w.Block($"{prefix} (obj is {v} {local})"))
                {
                    w.Line($"encoder.PushEnum({i}, {numBits});");
                    w.Line($"{v}.Encode_({local}, encoder);");
                }
            }
        }
        w.Line();

        // EncodeDiff
        using (w.Block($"public static byte[] EncodeDiff({def.SimpleName} a, {def.SimpleName} b)"))
        {
            w.Line("var encoder = new DeltaPack.Encoder();");
            // Variants are themselves tracked classes; read the snapshot's tracker via the
            // IDirtyTracked surface so we get the right per-domain baseline.
            w.Line("encoder.MinVersion = a is DeltaPack.IDirtyTracked __dp_a ? __dp_a.Tracker.GetBaselineFor(a) : -1;");
            w.Line("EncodeDiff_(a, b, encoder);");
            w.Line("return encoder.ToBuffer();");
        }
        w.Line();
        using (w.Block($"internal static void EncodeDiff_({def.SimpleName} a, {def.SimpleName} b, DeltaPack.Encoder encoder)"))
        {
            w.Line("encoder.PushBoolean(a.GetType() == b.GetType());");
            for (int i = 0; i < variants.Length; i++)
            {
                var v = variants[i];
                var prefix = i == 0 ? "if" : "else if";
                var lb = LocalName(Short(v)) + "B";
                var la = LocalName(Short(v)) + "A";
                using (w.Block($"{prefix} (b is {v} {lb})"))
                {
                    using (w.Block($"if (a is {v} {la})"))
                    {
                        w.Line($"{v}.EncodeDiff_({la}, {lb}, encoder);");
                    }
                    using (w.Block("else"))
                    {
                        w.Line($"encoder.PushEnum({i}, {numBits});");
                        w.Line($"{v}.Encode_({lb}, encoder);");
                    }
                }
            }
        }
        w.Line();

        // Decode
        using (w.Block($"public static {def.SimpleName} Decode(byte[] buf)"))
        {
            w.Line("return Decode(buf, DeltaPack.Tracker.Default);");
        }
        w.Line();
        using (w.Block($"public static {def.SimpleName} Decode(byte[] buf, DeltaPack.Tracker tracker)"))
        {
            w.Line("var decoder = new DeltaPack.Decoder(buf) { Tracker = tracker };");
            w.Line("return Decode_(decoder);");
        }
        w.Line();
        using (w.Block($"internal static {def.SimpleName} Decode_(DeltaPack.Decoder decoder)"))
        {
            w.Line($"var type = decoder.NextEnum({numBits});");
            for (int i = 0; i < variants.Length; i++)
            {
                var v = variants[i];
                var prefix = i == 0 ? "if" : "else if";
                w.Line($"{prefix} (type == {i}) return {v}.Decode_(decoder);");
            }
            w.Line($"throw new System.InvalidOperationException(\"Invalid {def.SimpleName} union\");");
        }
        w.Line();

        // DecodeDiff
        using (w.Block($"public static {def.SimpleName} DecodeDiff({def.SimpleName} obj, byte[] diff)"))
        {
            w.Line("var decoder = new DeltaPack.Decoder(diff);");
            w.Line("if (obj is DeltaPack.IDirtyTracked __dp_obj) decoder.Tracker = __dp_obj.Tracker;");
            w.Line("return DecodeDiff_(obj, decoder);");
        }
        w.Line();
        using (w.Block($"internal static {def.SimpleName} DecodeDiff_({def.SimpleName} obj, DeltaPack.Decoder decoder)"))
        {
            w.Line("var isSameType = decoder.NextBoolean();");
            using (w.Block("if (isSameType)"))
            {
                for (int i = 0; i < variants.Length; i++)
                {
                    var v = variants[i];
                    var local = LocalName(Short(v));
                    var prefix = i == 0 ? "if" : "else if";
                    w.Line($"{prefix} (obj is {v} {local}) return {v}.DecodeDiff_({local}, decoder);");
                }
                w.Line($"throw new System.InvalidOperationException(\"Invalid {def.SimpleName} diff\");");
            }
            using (w.Block("else"))
            {
                w.Line($"var type = decoder.NextEnum({numBits});");
                for (int i = 0; i < variants.Length; i++)
                {
                    var v = variants[i];
                    var prefix = i == 0 ? "if" : "else if";
                    w.Line($"{prefix} (type == {i}) return {v}.Decode_(decoder);");
                }
                w.Line($"throw new System.InvalidOperationException(\"Invalid {def.SimpleName} diff\");");
            }
        }
        w.Line();

        // CreateSyncSession — factory for the SyncSession wrapper using this type's
        // generated static methods as delegates.
        w.Line($"public static DeltaPack.SyncSession<{def.SimpleName}> CreateSyncSession()");
        w.Line($"    => CreateSyncSession(DeltaPack.Tracker.Default);");
        w.Line();
        w.Line($"public static DeltaPack.SyncSession<{def.SimpleName}> CreateSyncSession(DeltaPack.Tracker tracker)");
        w.Line($"    => new(tracker, Encode, buf => Decode(buf, tracker), EncodeDiff, DecodeDiff, Clone);");
    }

    private static string Short(string fqn)
    {
        var idx = fqn.LastIndexOf('.');
        return idx < 0 ? fqn : fqn.Substring(idx + 1);
    }

    private static string LocalName(string typeName)
        => char.ToLowerInvariant(typeName[0]) + typeName.Substring(1);
}
